name: "Pre-commit Action"
description: "Run pre-commit checks on code changes"
inputs:
  config_file:
    description: "Path to the pre-commit configuration file"
    required: false
  args:
    description: "Arguments to pass to pre-commit"
    required: false
    default: "--all-files"
  PYTHON_VERSION:
    required: false
    default: ""
  ROS_WORKSPACE:
    description: "Path to the ROS workspace"
    required: false
    default: "/opt/ros/noetic"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      if: ${{ inputs.PYTHON_VERSION != '' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
    - name: Install pre-requirements
      shell: bash
      run: |
          # Install apt requirements if file exists
          if [[ -f ./dev-requirements.apt ]]; then
            sudo apt-get update
            xargs -a ./dev-requirements.apt sudo apt-get install -y
          fi
    
          # Install pip requirements if file exists
          if [[ -f ./dev-requirements.txt ]]; then
            python3 -m pip install --upgrade pip
            python3 -m pip install -r ./dev-requirements.txt
          fi
          git config --global --add safe.directory $(pwd)
    - name: Run pre-commit
      shell: bash
      run: |
        if [[ -f ${{ inputs.ROS_WORKSPACE }}/setup.bash ]]; then
          echo "Sourcing ROS workspace"
          source ${{ inputs.ROS_WORKSPACE }}/setup.bash
        fi
        pre-commit run ${{ inputs.args }}
