repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-json                # checks if json files are valid
    - id: check-added-large-files   # checks if large files were added
    - id: check-merge-conflict      # checks if all merge conflicts were resolved
    - id: check-yaml                # checks if yaml files are valid
    - id: debug-statements          # checks if debug statements are to be commited
    - id: end-of-file-fixer         # fixes missing line ending in end of file
    - id: mixed-line-ending         # fixes line files line ending
      args: [--fix=lf]
    - id: trailing-whitespace       # removes trailing whitespaces from text files
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
        args:
          - -ignore  # Ignore SC2086: Double quote to prevent globbing and word splitting
          - SC2086
          - -ignore  # Ignore SC2206: Quote to prevent word splitting
          - SC2206
          - -ignore  # Ignore SC2046: Quote this to prevent word splitting
          - SC2046
          - -ignore  # Ignore 'label ".+" is unknown'
          - 'label ".+" is unknown'
          - -ignore  # Ignore SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects
          - SC2129
          - -ignore  # Ignore SC1083: This { is literal. Check expression (missing ;/\n?) or quote to prevent this.
          - SC1083
