name: Fetch PR Info
on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    outputs:
      pr_labels: 
        value: ${{ jobs.fetch_pr_info.outputs.pr_labels }}
      pr_number:
        value: ${{ jobs.fetch_pr_info.outputs.pr_number }}

jobs:
  fetch_pr_info:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr_info.outputs.pr_number }}
      pr_labels: ${{ steps.get_pr_info.outputs.pr_labels }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get PR Information
        id: get_pr_info
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        run: |
          # Check if workflow is triggered by a push event or a pull_request event
          if [[ ${{ github.event_name }} == "push" ]]; then
            # Get the commit SHA of the push
            COMMIT_SHA="${{ github.sha }}"
            # Get the commit message
            COMMIT_MESSAGE=$(git log -1 --format=%B "$COMMIT_SHA")
            echo "Commit message: $COMMIT_MESSAGE"
            # Check if this is a merge commit (a typical merge commit message contains "Merge pull request")
            if [[ "$COMMIT_MESSAGE" == Merge\ pull\ request* ]]; then
                # Extract the PR number from the commit message
                PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP '(?<=#)\d+')
                LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')

                echo "$(gh pr view $PR_NUMBER --json labels)"

                echo "PR number: $PR_NUMBER"
                echo "PR labels: $LABELS"

                # Set the PR number as an output
                echo "pr_number=" >> $GITHUB_OUTPUT
                echo "pr_labels='[${LABELS}]'" | tee >> $GITHUB_OUTPUT
            else
                echo "Not a merge commit."
                echo "pr_number=" >> $GITHUB_OUTPUT
                echo "pr_labels='[]'"  >> $GITHUB_OUTPUT
            fi
          elif [[ ${{ github.event_name }} == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            LABELS=$(echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | tr -d '[] ' | sed '/^$/d' | tr '\n' ','  | sed 's/^/[/' | sed 's/,$/]/')
            # Set the output values
            echo "pr_number=${PR_NUMBER}" | tee >> $GITHUB_OUTPUT
            echo "pr_labels='[${LABELS}]'" | tee >> $GITHUB_OUTPUT
          else
            echo "This is neither a push event nor a pull_request event."
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "pr_labels='[]'"  >> $GITHUB_OUTPUT
          fi


          
        
          
        
          