name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      promotion:
        required: true
        type: boolean
      deployment_app_name:
        required: true
        type: string
      aws_cluster_name:
        required: true
        type: string
      deployment_slack_channel:
        required: false
        type: string
        default: 'C05UYMX2U0K'
      aws_region:
        required: true
        type: string
    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      slack_token_id:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      gh_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_DEFAULT_REGION: ${{ secrets.aws_region }}

jobs:

  Deploy:
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/qa/tf-buildserver:v1.0.7
      credentials:
        username: ${{secrets.registry_user}}
        password: ${{secrets.registry_password}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set eks context and get pods
        shell: bash
        run: |
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ inputs.aws_cluster_name }}  
          kubectl get svc,po

      - name: Deploy Helm Chart
        shell: bash
        run: deploy.bash

      - name: Find Package details
        id: vars
        run: |
          PACKAGE_VERSION=$(cat version)
          echo ::set-output name=pkg_version::$PACKAGE_VERSION
  
      - name: Raise Version
        id: vars-after-raise
        run: |
          PACKAGE_VERSION=${{ steps.vars.outputs.pkg_version }}
          main_version=${PACKAGE_VERSION%-*}
          build_id="${PACKAGE_VERSION#*-}"
          raised_buildid=$(($build_id+1))
          RAISED_PACKAGE_VERSION="$main_version-$raised_buildid"
          echo $RAISED_PACKAGE_VERSION>version
          echo ::set-output name=pkg_version::$RAISED_PACKAGE_VERSION
  
      - name: Commit raise version
        id: raise
        if: ${{ inputs.promotion == false }}
        run: |
          git config --global user.name '${{ secrets.auto_commit_user }}'
          git config --global user.email '${{ secrets.auto_commit_mail }}'
          git config --global user.password ${{ secrets.auto_commit_pwd }}
          git pull
          git add version
          git commit -m "[skip actions] Automatic Bump of build version"
  
      - name: Prepare raise variables
        if: ${{ inputs.promotion == false }}
        id: pre_raise
        run: |
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          
      - name: Raise App version
        uses: CasperWA/push-protected@v2
        if: ${{ inputs.promotion == false }}
        with:
          token: ${{ secrets.auto_commit_pwd }}
          branch: ${{ steps.pre_raise.outputs.branch }}
          unprotect_reviews: true
      
      - name: Commit info
        id: commit
        if: ${{ inputs.promotion == false }}
        shell: bash
        run: |
          commit_hash=$(git log --format="%H" -n 1)
          echo ::set-output name=commit_id::$commit_hash
          
      - name: Create Github Release
        if: ${{ inputs.promotion == false }}
        uses: softprops/action-gh-release@v1
        with:
          name: "Deployment of ${{ steps.vars-after-raise.outputs.pkg_version }} of ${{ inputs.deployment_app_name }}"
          body: "Please add release notes"
          tag_name: ${{ steps.vars-after-raise.outputs.pkg_version }}
          target_commitish: ${{ steps.commit.outputs.commit_id }}
          token: ${{ secrets.gh_token }}
          prerelease: true
          generate_release_notes: true

      
      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "$job_id"
          echo "$job_html_url"
          echo "job_url=$job_html_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Prepare slack variables
        if: always()
        id: pre_slack_result
        run: |
          MESSAGE=":white_check_mark: Deployment of ${{ inputs.deployment_app_name }} successfull (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: Deployment of ${{ inputs.deployment_app_name }} failed (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Slack message success
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ inputs.deployment_slack_channel }}
          slack-text: ${{ steps.pre_slack_result.outputs.msg }}

      - name: Slack message failure
        uses: archive/github-actions-slack@master
        if: failure()
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ inputs.deployment_slack_channel }}
          slack-text: ${{ steps.pre_slack_result.outputs.msg_error }}
