name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      promotion:
        required: true
        type: boolean
      aws_cluster_name:
        required: true
        type: string
    
    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      gh_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_DEFAULT_REGION: ${{ secrets.aws_region }}

jobs:

  DeployHelmChart :
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/qa/tf-buildserver:v1.0.4
      credentials:
        username: ${{secrets.registry_user}}
        password: ${{secrets.registry_password}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set eks context and get pods
        shell: bash
        run: |
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ inputs.aws_cluster_name }}  
          kubectl get svc,po

      - name: Deploy Helm Chart
        shell: bash
        run: deploy.bash

      - name: Find Package details
        id: vars
        run: |
          PACKAGE_VERSION=$(cat version)
          echo ::set-output name=pkg_version::$PACKAGE_VERSION
  
      - name: Raise Version
        id: vars-after-raise
        run: |
          PACKAGE_VERSION=${{ steps.vars.outputs.pkg_version }}
          main_version=${PACKAGE_VERSION%-*}
          build_id="${PACKAGE_VERSION#*-}"
          raised_buildid=$(($build_id+1))
          RAISED_PACKAGE_VERSION="$main_version-$raised_buildid"
          echo $RAISED_PACKAGE_VERSION>version
          echo ::set-output name=pkg_version::$RAISED_PACKAGE_VERSION
  
      - name: Commit raise version
        id: raise
        run: |
          git config --global user.name '${{ secrets.auto_commit_user }}'
          git config --global user.email '${{ secrets.auto_commit_mail }}'
          git config --global user.password ${{ secrets.auto_commit_pwd }}
          git pull
          git add version
          git commit -m "[skip actions] Automatic Bump of build version"
  
      - name: Prepare raise variables
        id: pre_raise
        run: |
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          
      - name: Raise App version
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.auto_commit_pwd }}
          branch: ${{ steps.pre_raise.outputs.branch }}
          unprotect_reviews: true
      
      - name: Commit info
        id: commit
        shell: bash
        run: |
          commit_hash=$(git log --format="%H" -n 1)
          echo ::set-output name=commit_id::$commit_hash
          
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Deployment ${{ steps.vars-after-raise.outputs.pkg_version }}"
          body: "Please add release notes"
          tag_name: ${{ steps.vars-after-raise.outputs.pkg_version }}
          target_commitish: ${{ steps.commit.outputs.commit_id }}
          token: ${{ secrets.gh_token }}
          prerelease: true
          generate_release_notes: true

