name: Infrastructure Recreation
on:
  workflow_call:
    inputs:
      INFRA_IP_CONFIGURATION:
        required: true
        type: string
      INFRA_QA_CONFIGURATION:
        required: true
        type: string
      INFRA_NODES:
        required: true
        type: string

    secrets:
      auto_commit_user:
        required: true
      auto_commit_pwd:
        required: true
      aws_key_id:
        required: true
      aws_secret_key_id:
        required: true
      proxmox_ve_username:
        required: true
      proxmox_ve_password:
        required: true
      proxmox_hel0_ve_username:
        required: true
      proxmox_hel0_ve_password:
        required: true
      proxmox_hel1_ve_username:
        required: true
      proxmox_hel1_ve_password:
        required: true
      ssh_priv_key:
        required: true
      slack_token_id:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: "4.0.0.31"
  PROVISION_INFRA_REPO: "devops-tf-bpg-runners"
  PROVISION_INFRA_VERSION: "0.0.1-11"
  PROVISION_ENV_CONF_REPO: "devops-tf-env-conf"
  PROVISION_ENV_CONF_VERSION: "0.2.0-6"
  PROVISION_POOL: "GithubRunners"
  SLACK_CHANNEL: "G0102LEV1CL"
  #INFRA_NODES: '["hel0", "hel1"]'
  #INFRA_IP_CONFIGURATION: '{"hel0": 0,"hel1": 4}'
  #INFRA_QA_CONFIGURATION: '{"hel0": 0,"hel1": 1}'

jobs:
  Slack-thread:
    runs-on: ubuntu-latest
    outputs:
      slack_thread_id: ${{ fromJson(steps.send-message.outputs.response).ts }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreation in progress on ${{ inputs.INFRA_NODES }} :construction:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        id: send-message
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}"
            }

  Destroy-IP-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Destroy IP Runners
        id: destroy
        uses: ./.github/actions/infrastructure-teardown
        with:
          cluster_node: ${{ matrix.node }}
          infrastructure_identifier: "ip-runner-${{ matrix.node }}"
          provision_infra_repo: ${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version: ${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_env_repo: ${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_env_version: ${{ env.PROVISION_ENV_CONF_VERSION }}
          ci_integration_scripts_version: ${{ env.CI_INTEGRATION_SCRIPTS_VERSION }}
          github_api_user: ${{ secrets.auto_commit_user }}
          github_api_token: ${{ secrets.auto_commit_pwd }}
          proxmox_username: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_USERNAME || secrets.PROXMOX_HEL1_VE_USERNAME }}
          proxmox_password: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_PASSWORD || secrets.PROXMOX_HEL1_VE_PASSWORD }}
          proxmox_hel0_username: ${{ secrets.PROXMOX_HEL0_VE_USERNAME }}
          proxmox_hel0_password: ${{ secrets.PROXMOX_HEL0_VE_PASSWORD }}
          proxmox_hel1_username: ${{ secrets.PROXMOX_HEL1_VE_USERNAME }}
          proxmox_hel1_password: ${{ secrets.PROXMOX_HEL1_VE_PASSWORD }}
          aws_access_key: ${{ secrets.aws_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_key_id }}
          fleet_password: ""
          ssh_private_key: ${{ secrets.ssh_priv_key }}
          destroy_retry_attempts: "3"
          docker_container_version: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
          ci_integration_execution_folder: "$(pwd)/temp"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} IP runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy IP runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          printf 'msg_error=%s\n  Details: %s\n' "${MESSAGE_ERR}" "${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-IP-Runners:
    needs: [Destroy-IP-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}

    steps:
    - uses: actions/checkout@v4

    - name: Provision IP Runners
      id: provision
      uses: ./.github/actions/infrastructure-setup
      with:
        cluster_node: ${{ matrix.node }}
        infrastructure_identifier: "ip-runner-${{ matrix.node }}"
        fleet_usage: "ip-gh-runner"
        provision_infra_repo: ${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version: ${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_env_repo: ${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_env_version: ${{ env.PROVISION_ENV_CONF_VERSION }}
        ci_integration_scripts_version: ${{ env.CI_INTEGRATION_SCRIPTS_VERSION }}
        github_api_user: ${{ secrets.auto_commit_user }}
        github_api_token: ${{ secrets.auto_commit_pwd }}
        proxmox_username: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_USERNAME || secrets.PROXMOX_HEL1_VE_USERNAME }}
        proxmox_password: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_PASSWORD || secrets.PROXMOX_HEL1_VE_PASSWORD }}
        proxmox_hel0_username: ${{ secrets.PROXMOX_HEL0_VE_USERNAME }}
        proxmox_hel0_password: ${{ secrets.PROXMOX_HEL0_VE_PASSWORD }}
        proxmox_hel1_username: ${{ secrets.PROXMOX_HEL1_VE_USERNAME }}
        proxmox_hel1_password: ${{ secrets.PROXMOX_HEL1_VE_PASSWORD }}
        aws_access_key: ${{ secrets.aws_key_id }}
        aws_secret_key: ${{ secrets.aws_secret_key_id }}
        fleet_password: ""
        ssh_private_key: ${{ secrets.ssh_priv_key }}
        docker_container_version: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
        ci_integration_execution_folder: "$(pwd)/temp"
        custom_tfvars_content: |
          gh_access_token="${{ secrets.auto_commit_pwd }}"
          gh_runner_labels=["integration-pipeline-${{ matrix.node }}","integration-pipeline"]

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }} IP runners provisioned successfully in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision IP runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        printf 'msg_error=%s\n  Details: %s\n' "${MESSAGE_ERR}" "${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}"
          }

  Destroy-QA-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Destroy QA Runners
        id: destroy
        uses: ./.github/actions/infrastructure-teardown
        with:
          cluster_node: ${{ matrix.node }}
          infrastructure_identifier: "qa-runner-${{ matrix.node }}"
          provision_infra_repo: ${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version: ${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_env_repo: ${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_env_version: ${{ env.PROVISION_ENV_CONF_VERSION }}
          ci_integration_scripts_version: ${{ env.CI_INTEGRATION_SCRIPTS_VERSION }}
          github_api_user: ${{ secrets.auto_commit_user }}
          github_api_token: ${{ secrets.auto_commit_pwd }}
          proxmox_username: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_USERNAME || secrets.PROXMOX_HEL1_VE_USERNAME }}
          proxmox_password: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_PASSWORD || secrets.PROXMOX_HEL1_VE_PASSWORD }}
          proxmox_hel0_username: ${{ secrets.PROXMOX_HEL0_VE_USERNAME }}
          proxmox_hel0_password: ${{ secrets.PROXMOX_HEL0_VE_PASSWORD }}
          proxmox_hel1_username: ${{ secrets.PROXMOX_HEL1_VE_USERNAME }}
          proxmox_hel1_password: ${{ secrets.PROXMOX_HEL1_VE_PASSWORD }}
          aws_access_key: ${{ secrets.aws_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_key_id }}
          fleet_password: ""
          ssh_private_key: ${{ secrets.ssh_priv_key }}
          destroy_retry_attempts: "3"
          docker_container_version: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
          ci_integration_execution_folder: "$(pwd)/temp"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} QA runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy QA runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          printf 'msg_error=%s\n  Details: %s\n' "${MESSAGE_ERR}" "${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-QA-Runners:
    needs: [Destroy-QA-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}
    steps:
    - uses: actions/checkout@v4

    - name: Provision QA Runners
      id: provision
      uses: ./.github/actions/infrastructure-setup
      with:
        cluster_node: ${{ matrix.node }}
        infrastructure_identifier: "qa-runner-${{ matrix.node }}"
        fleet_usage: "ip-gh-runner"
        provision_infra_repo: ${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version: ${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_env_repo: ${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_env_version: ${{ env.PROVISION_ENV_CONF_VERSION }}
        ci_integration_scripts_version: ${{ env.CI_INTEGRATION_SCRIPTS_VERSION }}
        github_api_user: ${{ secrets.auto_commit_user }}
        github_api_token: ${{ secrets.auto_commit_pwd }}
        proxmox_username: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_USERNAME || secrets.PROXMOX_HEL1_VE_USERNAME }}
        proxmox_password: ${{ matrix.node == 'hel0' && secrets.PROXMOX_HEL0_VE_PASSWORD || secrets.PROXMOX_HEL1_VE_PASSWORD }}
        proxmox_hel0_username: ${{ secrets.PROXMOX_HEL0_VE_USERNAME }}
        proxmox_hel0_password: ${{ secrets.PROXMOX_HEL0_VE_PASSWORD }}
        proxmox_hel1_username: ${{ secrets.PROXMOX_HEL1_VE_USERNAME }}
        proxmox_hel1_password: ${{ secrets.PROXMOX_HEL1_VE_PASSWORD }}
        aws_access_key: ${{ secrets.aws_key_id }}
        aws_secret_key: ${{ secrets.aws_secret_key_id }}
        fleet_password: ""
        ssh_private_key: ${{ secrets.ssh_priv_key }}
        docker_container_version: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
        ci_integration_execution_folder: "$(pwd)/temp"
        custom_tfvars_content: |
          gh_access_token="${{ secrets.auto_commit_pwd }}"
          gh_runner_labels=["qa-pipeline-${{ matrix.node }}","qa-pipeline","qa-runner"]

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }} QA runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision QA runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        printf 'msg_error=%s\n  Details: %s\n' "${MESSAGE_ERR}" "${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}"
          }

  Run-Status:
    needs: [Provision-IP-Runners, Provision-QA-Runners]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreated successfully  on ${{ inputs.INFRA_NODES }} ! :sunny:"
          MESSAGE_ERR="Infrastructure recreation failed  on ${{ inputs.INFRA_NODES }} ! :rain_cloud:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_err=${MESSAGE_ERR}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        if: ${{ needs.Provision-IP-Runners.result == 'success' && needs.Provision-QA-Runners.result == 'success' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.update
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "ts": "${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}",
              "text": "${{ steps.pre_slack.outputs.msg }}"
            }

      - name: Send Slack Message
        if: ${{ always() && (! needs.Provision-IP-Runners.result == 'success' || ! needs.Provision-QA-Runners.result == 'success') }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.update
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "ts": "${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}",
              "text": "${{ steps.pre_slack.outputs.msg_err }}"
            }
