name: Infrastructure Recreation
on:
  workflow_call:
    inputs:
      INFRA_IP_CONFIGURATION:
        required: true
        type: string
      INFRA_QA_CONFIGURATION:
        required: true
        type: string
      INFRA_ROBOTICS_SIM_CONFIGURATION:
        required: true
        type: string
      INFRA_REDHAT_ORACLE_CONFIGURATION:
        required: true
        type: string
      INFRA_PACKER_CONFIGURATION:
        required: true
        type: string
      INFRA_NODES:
        required: true
        type: string

    secrets:
      auto_commit_user:
        required: true
      auto_commit_pwd:
        required: true
      aws_key_id:
        required: true
      aws_secret_key_id:
        required: true
      proxmox_ve_username:
        required: true
      proxmox_ve_password:
        required: true
      ssh_priv_key:
        required: true
      slack_token_id:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: "4.0.0.31"
  PROVISION_INFRA_REPO: "devops-tf-bpg-runners"
  PROVISION_INFRA_VERSION: "0.1.0-1"
  PROVISION_ENV_CONF_REPO: "devops-tf-env-conf"
  PROVISION_ENV_CONF_VERSION: "0.2.2-2"
  PROVISION_POOL: "GithubRunners"
  SLACK_CHANNEL: "G0102LEV1CL"
  NAMES_PREFIX: "ng-" # temporary to avoid conflicts with existing runners, can be removed once we validated new infrastructure
  # INFRA_NODES: '["hel0", "hel1"]'
  # INFRA_IP_CONFIGURATION: '{"hel0": 2,"hel1": 8}'
  # INFRA_QA_CONFIGURATION: '{"hel0": 1,"hel1": 2}'
  # INFRA_ROBOTICS_SIM_CONFIGURATION: '{"hel0": 1,"hel1": 1}'
  # INFRA_REDHAT_ORACLE_CONFIGURATION: '{"hel0": 1,"hel1": 1}'
  # INFRA_PACKER_CONFIGURATION: '{"hel0": 1,"hel1": 1}'

jobs:
  Slack-thread:
    runs-on: ubuntu-latest
    outputs:
      slack_thread_id: ${{ fromJson(steps.send-message.outputs.response).ts }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreation in progress on ${{ inputs.INFRA_NODES }} :construction:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        id: send-message
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}"
            }

  Destroy-IP-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:
      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          desired_profile='gh_runner'
          base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
          selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
          if [[ ! -f "${selected_var_file}" ]]; then
            echo "Missing tfvars file: ${selected_var_file}" >&2
            exit 1
          fi
          var_file_arg="-var-file=${selected_var_file}"
          echo "Selected tfvars: ${selected_var_file}"

          {
            echo "proxmox_host_list=[$node_list_str]"
            echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}"'
            echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-ip-runner"'
          } >> input.tfvars
          echo "ip_list=[$ip_list_str]">>input.tfvars
          echo 'tags=["ip-runner"]'>>input.tfvars
          echo 'pool="${{ env.PROVISION_POOL }}"'>>input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
          echo 'gh_runner_labels=["integration-pipeline-${{ matrix.node }}"]'>>input.tfvars


          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-ip-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} IP runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy IP runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-IP-Runners:
    needs: [Destroy-IP-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}

    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        desired_profile='gh_runner'
        base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
        selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
        if [[ ! -f "${selected_var_file}" ]]; then
          echo "Missing tfvars file: ${selected_var_file}" >&2
          exit 1
        fi
        var_file_arg="-var-file=${selected_var_file}"
        echo "Selected tfvars: ${selected_var_file}"

        echo "proxmox_host_list=[$node_list_str]">>input.tfvars
        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
        echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-ip-runner"'>>input.tfvars
        echo "ip_list=[$ip_list_str]">>input.tfvars
        echo 'tags=["ip-runner"]'>>input.tfvars
        echo 'pool="${{ env.PROVISION_POOL }}"'>>input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
        echo 'gh_runner_labels=["integration-pipeline-${{ matrix.node }}","integration-pipeline"]'>>input.tfvars
        echo 'cloud_init_packages=["python3-dev","build-essential"]'>>input.tfvars


        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-ip-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }} IP runners provisioned successfully in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision IP runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}"
          }

  Destroy-QA-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:

      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          desired_profile='gh_runner'
          base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
          selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
          if [[ ! -f "${selected_var_file}" ]]; then
            echo "Missing tfvars file: ${selected_var_file}" >&2
            exit 1
          fi
          var_file_arg="-var-file=${selected_var_file}"
          echo "Selected tfvars: ${selected_var_file}"


          echo "proxmox_host_list=[$node_list_str]">>input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
          echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-qa-runner"'>>input.tfvars
          echo "ip_list=[$ip_list_str]">>input.tfvars
          echo 'tags=["ip-runner"]'>>input.tfvars
          echo 'pool="${{ env.PROVISION_POOL }}"'>>input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
          echo 'gh_runner_labels=["qa-pipeline-${{ matrix.node }}"]'>>input.tfvars


          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-qa-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} QA runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy QA runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-QA-Runners:
    needs: [Destroy-QA-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}
    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        desired_profile='gh_runner'
        base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
        selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
        if [[ ! -f "${selected_var_file}" ]]; then
          echo "Missing tfvars file: ${selected_var_file}" >&2
          exit 1
        fi
        var_file_arg="-var-file=${selected_var_file}"
        echo "Selected tfvars: ${selected_var_file}"

        echo "proxmox_host_list=[$node_list_str]">>input.tfvars
        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
        echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-qa-runner"'>>input.tfvars
        echo "ip_list=[$ip_list_str]">>input.tfvars
        echo 'tags=["ip-runner"]'>>input.tfvars
        echo 'pool="${{ env.PROVISION_POOL }}"'>>input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
        echo 'gh_runner_labels=["qa-pipeline-${{ matrix.node }}","qa-pipeline","qa-runner"]'>>input.tfvars
        echo 'cloud_init_packages=["python3-dev","build-essential"]'>>input.tfvars


        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-qa-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }} QA runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision QA runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}"
          }

  Destroy-Robotics-Sim-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:

      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          desired_profile='gh_sim_runner'
          base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
          selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
          if [[ ! -f "${selected_var_file}" ]]; then
            echo "Missing tfvars file: ${selected_var_file}" >&2
            exit 1
          fi
          var_file_arg="-var-file=${selected_var_file}"
          echo "Selected tfvars: ${selected_var_file}"


          echo "proxmox_host_list=[$node_list_str]" >> input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
          echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-robotics-sim-runner"' >> input.tfvars
          echo "ip_list=[$ip_list_str]" >> input.tfvars
          echo 'tags=["robotics-sim-runner"]' >> input.tfvars
          echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
          echo 'gh_runner_labels=["robotics-sim-runner-${{ matrix.node }}"]' >> input.tfvars
          echo "\n" >> input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-robotics-sim-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} Robotics Sim runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy Robotics Sim runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-Robotics-Sim-Runners:
    needs: [Destroy-Robotics-Sim-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-Robotics-Sim-Runners.outputs.slack_thread_id }}
    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        desired_profile='gh_sim_runner'
        base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
        selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
        if [[ ! -f "${selected_var_file}" ]]; then
          echo "Missing tfvars file: ${selected_var_file}" >&2
          exit 1
        fi
        var_file_arg="-var-file=${selected_var_file}"
        echo "Selected tfvars: ${selected_var_file}"

        echo "proxmox_host_list=[$node_list_str]" >> input.tfvars
        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
        echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-robotics-sim-runner"' >> input.tfvars
        echo "ip_list=[$ip_list_str]" >> input.tfvars
        echo 'tags=["robotics-sim-runner"]' >> input.tfvars
        echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
        echo 'gh_runner_labels=["robotics-sim-runner-${{ matrix.node }}","robotics-sim-runner"]' >> input.tfvars
        echo 'cloud_init_packages=["python3-dev","build-essential"]'>>input.tfvars
        echo "\n" >> input

        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-robotics-sim-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_ROBOTICS_SIM_CONFIGURATION)[matrix.node] }} Robotics Sim runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision Robotics Sim runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-Robotics-Sim-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-Robotics-Sim-Runners.outputs.slack_thread_id }}"
          }

  Destroy-Redhat-Oracle-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:

      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          desired_profile='gh_redhat_oracle_runner'
          base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
          selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
          if [[ ! -f "${selected_var_file}" ]]; then
            echo "Missing tfvars file: ${selected_var_file}" >&2
            exit 1
          fi
          var_file_arg="-var-file=${selected_var_file}"
          echo "Selected tfvars: ${selected_var_file}"


          echo "proxmox_host_list=[$node_list_str]" >> input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
          echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-redhat-oracle-runner"' >> input.tfvars
          echo "ip_list=[$ip_list_str]" >> input.tfvars
          echo 'tags=["redhat-oracle-runner"]' >> input.tfvars
          echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
          echo 'gh_runner_labels=["redhat-oracle-runner-${{ matrix.node }}"]' >> input.tfvars
          echo "\n" >> input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-redhat-oracle-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} Redhat Oracle runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy Redhat Oracle runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-Redhat-Oracle-Runners:
    needs: [Destroy-Redhat-Oracle-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-Redhat-Oracle-Runners.outputs.slack_thread_id }}
    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        desired_profile='gh_redhat_oracle_runner'
        base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
        selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
        if [[ ! -f "${selected_var_file}" ]]; then
          echo "Missing tfvars file: ${selected_var_file}" >&2
          exit 1
        fi
        var_file_arg="-var-file=${selected_var_file}"
        echo "Selected tfvars: ${selected_var_file}"

        echo "proxmox_host_list=[$node_list_str]" >> input.tfvars
        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
        echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-redhat-oracle-runner"' >> input.tfvars
        echo "ip_list=[$ip_list_str]" >> input.tfvars
        echo 'tags=["redhat-oracle-runner"]' >> input.tfvars
        echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
        echo 'gh_runner_labels=["redhat-oracle-runner-${{ matrix.node }}","redhat-oracle-runner"]' >> input.tfvars
        echo 'cloud_init_packages=["python3-dev","build-essential"]'>>input.tfvars
        echo "\n" >> input

        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-redhat-oracle-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_REDHAT_ORACLE_CONFIGURATION)[matrix.node] }} Redhat Oracle runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision Redhat Oracle runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-Redhat-Oracle-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-Redhat-Oracle-Runners.outputs.slack_thread_id }}"
          }

  Destroy-Packer-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:

      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          desired_profile='gh_packer_runner'
          base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
          selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
          if [[ ! -f "${selected_var_file}" ]]; then
            echo "Missing tfvars file: ${selected_var_file}" >&2
            exit 1
          fi
          var_file_arg="-var-file=${selected_var_file}"
          echo "Selected tfvars: ${selected_var_file}"


          echo "proxmox_host_list=[$node_list_str]" >> input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
          echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-packer-runner"' >> input.tfvars
          echo "ip_list=[$ip_list_str]" >> input.tfvars
          echo 'tags=["packer-runner"]' >> input.tfvars
          echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
          echo 'gh_runner_labels=["packer-runner-${{ matrix.node }}"]' >> input.tfvars
          echo "\n" >> input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-packer-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} Packer runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy Packer runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack.outputs.msg_error }}",
              "thread_ts": "${{ needs.Slack-thread.outputs.slack_thread_id }}"
            }

  Provision-Packer-Runners:
    needs: [Destroy-Packer-Runners]
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-Packer-Runners.outputs.slack_thread_id }}
    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        desired_profile='gh_packer_runner'
        base_var_dir="../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel"
        selected_var_file="${base_var_dir}/${{ matrix.node }}_${desired_profile}.tfvars"
        if [[ ! -f "${selected_var_file}" ]]; then
          echo "Missing tfvars file: ${selected_var_file}" >&2
          exit 1
        fi
        var_file_arg="-var-file=${selected_var_file}"
        echo "Selected tfvars: ${selected_var_file}"

        echo "proxmox_host_list=[$node_list_str]" >> input.tfvars
        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }}"' >> input.tfvars
        echo 'gh_runner_name_prefix="${{ env.NAMES_PREFIX }}${{ matrix.node }}-packer-runner"' >> input.tfvars
        echo "ip_list=[$ip_list_str]" >> input.tfvars
        echo 'tags=["packer-runner"]' >> input.tfvars
        echo 'pool="${{ env.PROVISION_POOL }}"' >> input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"' >> input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"' >> input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"' >> input.tfvars
        echo 'gh_runner_labels=["packer-runner-${{ matrix.node }}","packer-runner"]' >> input.tfvars
        echo 'cloud_init_packages=["python3-dev","build-essential"]'>>input.tfvars
        echo "\n" >> input

        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ env.NAMES_PREFIX }}${{ matrix.node }}-packer-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_PACKER_CONFIGURATION)[matrix.node] }} Packer runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision Packer runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg }}",
            "thread_ts": "${{ needs.Destroy-Packer-Runners.outputs.slack_thread_id }}"
          }

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      if: ${{ failure() }}
      with:
        method: chat.postMessage
        token: ${{ secrets.slack_token_id }}
        payload: |
          {
            "channel": "${{ env.SLACK_CHANNEL }}",
            "text": "${{ steps.pre_slack.outputs.msg_error }}",
            "thread_ts": "${{ needs.Destroy-Packer-Runners.outputs.slack_thread_id }}"
          }

  Run-Status:
    needs: [Provision-IP-Runners, Provision-QA-Runners, Provision-Robotics-Sim-Runners, Provision-Redhat-Oracle-Runners, Provision-Packer-Runners]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreated successfully  on ${{ inputs.INFRA_NODES }} ! :sunny:"
          MESSAGE_ERR="Infrastructure recreation failed  on ${{ inputs.INFRA_NODES }} ! :rain_cloud:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_err=${MESSAGE_ERR}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        if: ${{ needs.Provision-IP-Runners.result == 'success' && needs.Provision-QA-Runners.result == 'success' && needs.Provision-Robotics-Sim-Runners.result == 'success' && needs.Provision-Redhat-Oracle-Runners.result == 'success' && needs.Provision-Packer-Runners.result == 'success' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.update
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "ts": "${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}",
              "text": "${{ steps.pre_slack.outputs.msg }}"
            }

      - name: Send Slack Message
        if: ${{ always() && (! needs.Provision-IP-Runners.result == 'success' || ! needs.Provision-QA-Runners.result == 'success' || ! needs.Provision-Robotics-Sim-Runners.result == 'success' || ! needs.Provision-Redhat-Oracle-Runners.result == 'success' || ! needs.Provision-Packer-Runners.result == 'success') }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.update
          token: ${{ secrets.slack_token_id }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "ts": "${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}",
              "text": "${{ steps.pre_slack.outputs.msg_err }}"
            }
