name: Infrastructure Recreation
on:
  workflow_call:
    inputs:
      INFRA_IP_CONFIGURATION:
        required: true
        type: string
      INFRA_QA_CONFIGURATION:
        required: true
        type: string
      INFRA_NODES:
        required: true
        type: string

    secrets:
      auto_commit_user:
        required: true
      auto_commit_pwd:
        required: true
      aws_key_id:
        required: true
      aws_secret_key_id:
        required: true
      proxmox_ve_username:
        required: true
      proxmox_ve_password:
        required: true
      ssh_priv_key:
        required: true
      slack_token_id:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: "4.0.0.31"
  PROVISION_INFRA_REPO: "devops-tf-bpg-runners"
  PROVISION_INFRA_VERSION: "0.0.1-9"
  PROVISION_ENV_CONF_REPO: "devops-tf-env-conf"
  PROVISION_ENV_CONF_VERSION: "0.1.0-17"
  SLACK_CHANNEL: "G0102LEV1CL"
  #INFRA_NODES: '["hel0", "hel1"]'
  #INFRA_IP_CONFIGURATION: '{"hel0": 0,"hel1": 4}'
  #INFRA_QA_CONFIGURATION: '{"hel0": 0,"hel1": 1}'

jobs:
  Slack-thread:
    runs-on: ubuntu-latest
    outputs:
      slack_thread_id: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreation in progress :construction:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ steps.pre_slack.outputs.msg }}

  Destroy-IP-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:
      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          var_file_arg='-var-file=../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel/${{ matrix.node }}_gh_runner.tfvars'


          echo "proxmox_host_list=[$node_list_str]">>input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
          echo 'gh_runner_name_prefix="${{ matrix.node }}-ip-runner"'>>input.tfvars
          echo "ip_list=[$ip_list_str]">>input.tfvars
          echo 'tags=["ip-runner"]'>>input.tfvars
          echo 'pool="IP-Temp-VMs"'>>input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
          echo 'gh_runner_labels=["integration-pipeline-${{ matrix.node }}"]'>>input.tfvars
          echo "\n">>input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ matrix.node }}-ip-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |          
          job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} IP runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy IP runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ steps.pre_slack.outputs.msg }}
          slack-optional-thread_ts: ${{ needs.Slack-thread.outputs.slack_thread_id }}

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        if: ${{ failure() }}
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ steps.pre_slack.outputs.msg_error }}
          slack-optional-thread_ts: ${{ needs.Slack-thread.outputs.slack_thread_id }}


  Provision-IP-Runners:
    needs: Destroy-IP-Runners
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}

    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        var_file_arg='-var-file=../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel/${{ matrix.node }}_gh_runner.tfvars'


        echo "proxmox_host_list=[$node_list_str]">>input.tfvars

        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
        echo 'gh_runner_name_prefix="${{ matrix.node }}-ip-runner"'>>input.tfvars
        echo "ip_list=[$ip_list_str]">>input.tfvars
        echo 'tags=["ip-runner"]'>>input.tfvars
        echo 'pool="IP-Temp-VMs"'>>input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
        echo 'gh_runner_labels=["integration-pipeline-${{ matrix.node }}","integration-pipeline"]'>>input.tfvars
        echo "\n">>input

        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ matrix.node }}-ip-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_IP_CONFIGURATION)[matrix.node] }} IP runners provisioned successfully in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision IP runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
        slack-channel: ${{ env.SLACK_CHANNEL }}
        slack-text: ${{ steps.pre_slack.outputs.msg }}
        slack-optional-thread_ts: ${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}

    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      if: ${{ failure() }}
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
        slack-channel: ${{ env.SLACK_CHANNEL }}
        slack-text: ${{ steps.pre_slack.outputs.msg_error }}
        slack-optional-thread_ts: ${{ needs.Destroy-IP-Runners.outputs.slack_thread_id }}

  Destroy-QA-Runners:
    needs: Slack-thread
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Slack-thread.outputs.slack_thread_id }}

    steps:

      - name: Setup CI Scripts in .ci-venv
        shell: bash
        run: |
          cat << EOF | sudo tee /etc/pip.conf
          [global]
          index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
          extra-index-url = https://pypi.org/simple
          trusted-host = artifacts.cloud.mov.ai
                        pypi.org
          EOF
          cat /etc/pip.conf
          python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
          . .ci-venv/bin/activate
          python3 -m pip install pyOpenSSL --upgrade pip
          [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

      - name: Setup env conf
        id: provision_infra_env_conf
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
          provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          . .ci-venv/bin/activate
          provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user ${{ secrets.auto_commit_user }} \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Destroy remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
          node_list_str=${multiply_node::-1}
          multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
          ip_list_str=${multiply_ips::-1}
          var_file_arg='-var-file=../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel/${{ matrix.node }}_gh_runner.tfvars'


          echo "proxmox_host_list=[$node_list_str]">>input.tfvars

          echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
          echo 'gh_runner_name_prefix="${{ matrix.node }}-qa-runner"'>>input.tfvars
          echo "ip_list=[$ip_list_str]">>input.tfvars
          echo 'tags=["ip-runner"]'>>input.tfvars
          echo 'pool="IP-Temp-VMs"'>>input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
          echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
          echo 'gh_runner_labels=["qa-pipeline-${{ matrix.node }}"]'>>input.tfvars
          echo "\n">>input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ matrix.node }}-qa-runners.tfstate"
          terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Get current job id
        if: always()
        shell: bash
        id: job_info
        run: |
          job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
          echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: ${{ github.job }} ${{ matrix.node }} QA runners destroyed (Attempt: #${{ github.run_attempt }})"
          MESSAGE_ERR=":x: ${{ github.job }} ${{ matrix.node }} Failed to destroy QA runners (Attempt: #${{ github.run_attempt }})"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ steps.pre_slack.outputs.msg }}
          slack-optional-thread_ts: ${{ needs.Slack-thread.outputs.slack_thread_id }}

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        if: ${{ failure() }}
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ steps.pre_slack.outputs.msg_error }}
          slack-optional-thread_ts: ${{ needs.Slack-thread.outputs.slack_thread_id }}

  Provision-QA-Runners:
    needs: Destroy-QA-Runners
    runs-on: infra-runner
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON( inputs.INFRA_NODES ) }}
    outputs:
      slack_thread_id: ${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}
    steps:

    - name: Setup CI Scripts in .ci-venv
      shell: bash
      run: |
        cat << EOF | sudo tee /etc/pip.conf
        [global]
        index-url = https://artifacts.aws.cloud.mov.ai/repository/pypi-integration/simple
        extra-index-url = https://pypi.org/simple
        trusted-host = artifacts.cloud.mov.ai
                      pypi.org
        EOF
        cat /etc/pip.conf
        python3 -m venv .ci-venv --clear --system-site-packages # needed for apt dependencies
        . .ci-venv/bin/activate
        python3 -m pip install pyOpenSSL --upgrade pip
        [ -f ci-requirements.txt ] && pip install -r ci-requirements.txt
        python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed

    - name: Setup env conf
      id: provision_infra_env_conf
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_ENV_CONF_REPO }}
        provision_infra_version=${{ env.PROVISION_ENV_CONF_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_ENV_CONF_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Setup terraform proxmox provisioner
      id: provision_infra_setup
      shell: bash
      run: |
        . .ci-venv/bin/activate
        provision_infra_dir=${{ env.PROVISION_INFRA_REPO }}
        provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
        provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

        rm -rf $provision_infra_dir
        integration-pipeline fetch_by_tag --repo $provision_infra_repo_name \
          --version $provision_infra_version \
          --gh_api_user ${{ secrets.auto_commit_user }} \
          --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
          --target_dir $provision_infra_dir

        ls -la $provision_infra_dir
        echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

    - name: Provision remote vms (Proxmox)
      working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
      shell: bash
      run: |
        multiply_node=$(printf '"${{ matrix.node }}",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
        node_list_str=${multiply_node::-1}
        multiply_ips=$(printf '"dhcp",%.0s' {1..${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}})
        ip_list_str=${multiply_ips::-1}
        var_file_arg='-var-file=../${{ steps.provision_infra_env_conf.outputs.target_dir }}/hel/${{ matrix.node }}_gh_runner.tfvars'


        echo "proxmox_host_list=[$node_list_str]">>input.tfvars

        echo 'gh_runner_nr="${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }}"'>>input.tfvars
        echo 'gh_runner_name_prefix="${{ matrix.node }}-qa-runner"'>>input.tfvars
        echo "ip_list=[$ip_list_str]">>input.tfvars
        echo 'tags=["ip-runner"]'>>input.tfvars
        echo 'pool="IP-Temp-VMs"'>>input.tfvars
        echo 'proxmox_ve_username="${{ secrets.proxmox_ve_username }}"'>>input.tfvars
        echo 'proxmox_ve_password="${{ secrets.proxmox_ve_password }}"'>>input.tfvars
        echo 'gh_access_token="${{ secrets.auto_commit_pwd }}"'>>input.tfvars
        echo 'gh_runner_labels=["qa-pipeline-${{ matrix.node }}","qa-pipeline","qa-runner"]'>>input.tfvars
        echo "\n">>input

        echo "File args: $var_file_arg"
        echo "Input File args: $(cat input.tfvars)"
        terraform init -backend-config="key=${{ matrix.node }}-qa-runners.tfstate"
        terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
        terraform refresh $var_file_arg -var-file=input.tfvars

        echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
        sudo chmod 600 ~/.ssh/ci_priv_key.pem

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Get current job id
      if: always()
      shell: bash
      id: job_info
      run: |
        job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
        job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
        echo "job_url=$job_html_url" | tee >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}

    - name: Prepare slack variables
      if: ${{ always() }}
      id: pre_slack
      run: |
        MESSAGE=":white_check_mark: ${{ github.job }} ${{ fromJson(inputs.INFRA_QA_CONFIGURATION)[matrix.node] }} QA runners provisioned successfully in ${{matrix.node}}! (Attempt: #${{ github.run_attempt }})"
        MESSAGE_ERR=":x: ${{ github.job }} Failed to provision QA runners in ${{ matrix.node }}! (Attempt: #${{ github.run_attempt }})"
        echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
        echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
        slack-channel: ${{ env.SLACK_CHANNEL }}
        slack-text: ${{ steps.pre_slack.outputs.msg }}
        slack-optional-thread_ts: ${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}

    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      if: ${{ failure() }}
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
        slack-channel: ${{ env.SLACK_CHANNEL }}
        slack-text: ${{ steps.pre_slack.outputs.msg_error }}
        slack-optional-thread_ts: ${{ needs.Destroy-QA-Runners.outputs.slack_thread_id }}

  Run-Status:
    needs: [Provision-IP-Runners, Provision-QA-Runners]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Prepare slack variables
        if: ${{ always() }}
        id: pre_slack
        run: |
          MESSAGE="Infrastructure recreated successfully! :sunny:"
          MESSAGE_ERR="Infrastructure recreation failed! :rain_cloud:"
          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
          echo "msg_err=${MESSAGE_ERR}" >> $GITHUB_OUTPUT

      - name: Send Slack Message
        if: ${{ needs.Provision-IP-Runners.result == 'success' && needs.Provision-QA-Runners.result == 'success' }}
        uses: archive/github-actions-slack@master
        with:
          slack-function: update-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-update-message-text: ${{ steps.pre_slack.outputs.msg }}
          slack-update-message-ts: ${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}

      - name: Send Slack Message
        if: ${{ always() && (! needs.Provision-IP-Runners.result == 'success' || ! needs.Provision-QA-Runners.result == 'success') }}
        uses: archive/github-actions-slack@master
        with:
          slack-function: update-message
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-update-message-text: ${{ steps.pre_slack.outputs.msg_err }}
          slack-update-message-ts: ${{ needs.Provision-IP-Runners.outputs.slack_thread_id }}
