name: Robotic Component pipeline
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      vs_product_name:
        required: true
        type: string
      vs_product_version_pattern:
        required: true
        type: string
      test_repo_name:
        required: true
        type: string
      test_version:
        required: true
        type: string
      test_set:
        required: true
        type: string
      cluster:
        required: false
        default: "mary"
        type: string
      debug_component_tests_keep_alive:
        required: false
        default: false
        type: boolean

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      aws_key_id:
        required: true
      aws_secret_key_id:
        required: true
      proxmox_ve_sim_username:
        required: true
      proxmox_ve_sim_password:
        required: true
      ssh_priv_key:
        required: true
      slack_token_id:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: "4.0.0.13"
  GITHUB_API_USR: "OttoMation-Movai"
  USERSPACE_FOLDER_PATH: "$(pwd)/userspace"
  REMOTE_WORKSPACE_PATH: workspace
  CI_INTEGRATION_CONTAINER_VERSION: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
  CI_INTEGRATION_CONTAINER_WORKSPACE: "/opt/mov.ai/workspace"
  CI_INTEGRATION_EXECUTION_FOLDER: "$(pwd)/temp"
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key_id }}
  AWS_DEFAULT_REGION: "us-east-1"
  REGISTRY: registry.cloud.mov.ai
  PROVISION_INFRA_REPO: "devops-tf-proxmox-bpg"
  PROVISION_INFRA_VERSION: "2.0.0-3"
  PROVISION_INFRA_DIR: "provision_scripts"
  PROVISIONING_ENV_CONF_REPO: "devops-tf-env-conf"
  PROVISIONING_ENV_CONF_VERSION: "0.1.0-15"
  PROVISION_ENV_CONF_DIR: "infra_env_configs"
  SIMULATION_ID: CI

jobs:
  Platform-tests:
    runs-on: simul-${{ inputs.cluster }}-queuer

    steps:
      - name: Cleanup Workspace
        uses: rtCamp/action-cleanup@master

      - name: Checkout
        uses: actions/checkout@v4



      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}
          registry: ${{ env.REGISTRY }}

      - name: Create execution folder
        shell: bash
        run: |
          sudo rm -rf ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
          mkdir  -p ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
          sudo chmod -R 777 ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

      - name: Setup infra environment configs
        id: infra_env_configs_setup
        shell: bash
        run: |
          env_configs_dir=${{ env.PROVISION_ENV_CONF_DIR }}
          env_configs_version=${{ env.PROVISIONING_ENV_CONF_VERSION }}
          env_configs_repo_name=${{ env.PROVISIONING_ENV_CONF_REPO }}

          rm -rf $env_configs_dir
          docker run \
            -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }} \
            -i ${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
            fetch_by_tag --repo $env_configs_repo_name \
            --version $env_configs_version \
            --gh_api_user $GITHUB_API_USR \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $env_configs_dir
          cp -r ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/$env_configs_dir ./$env_configs_dir
          
          ls -la $env_configs_dir
          echo "target_dir=${env_configs_dir}" >> $GITHUB_OUTPUT

      - name: Setup terraform proxmox provisioner
        id: provision_infra_setup
        shell: bash
        run: |
          provision_infra_dir=${{ env.PROVISION_INFRA_DIR }}
          provision_infra_version=${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_repo_name=${{ env.PROVISION_INFRA_REPO }}

          rm -rf $provision_infra_dir
          docker run \
            -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }} \
            -i ${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
            fetch_by_tag --repo $provision_infra_repo_name \
            --version $provision_infra_version \
            --gh_api_user $GITHUB_API_USR \
            --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
            --target_dir $provision_infra_dir
          cp -r ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/$provision_infra_dir ./$provision_infra_dir

          ls -la $provision_infra_dir
          echo "target_dir=${provision_infra_dir}" >> $GITHUB_OUTPUT

      - name: Define Instance names
        id: infra_names
        shell: bash
        run: |
          BRANCH=${{ github.base_ref }}
          # Remove branch prefix 
          branch=${BRANCH#*/}
          branch=$(echo ${branch} | sed "s;\.;-;g" )

          run_type="ci"

          local_manager_prefix="ip-$run_type-${{ inputs.cluster }}-${{ inputs.component_name }}-$branch"

          tf_state="${{ inputs.cluster }}-sim-$local_manager_prefix"
          echo "simul_prefix=${local_manager_prefix}" | tee >> $GITHUB_OUTPUT
          echo "tfstate_name=${tf_state}" | tee >> $GITHUB_OUTPUT


      - name: Provision remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        shell: bash
        run: |
          multiply_node=$(printf '"${{ inputs.cluster }}",%.0s' {1..1})
          node_list_str=${multiply_node::-1}

          var_file_arg='-var-file=../${{ steps.infra_env_configs_setup.outputs.target_dir }}/marvin/${{ inputs.cluster }}_simul_bpg.tfvars'

          echo "proxmox_host_list=[$node_list_str]">>input.tfvars
          echo "fleet_peer_nr=0">>input.tfvars
          echo 'fleet_password="${{ secrets.provision_infra_pwd }}"'>>input.tfvars
          echo 'fleet_manager_name="${{ steps.infra_names.outputs.simul_prefix }}"'>>input.tfvars
          echo 'ip_list=["dhcp"]'>>input.tfvars
          echo 'tags=["ip-simul-ci"]'>>input.tfvars
          echo 'pool="IP-Temp-VMs"'>>input.tfvars
          echo 'proxmox_ve_username="${{ secrets.proxmox_ve_sim_username }}"'>>input.tfvars
          echo 'proxmox_ve_password="${{ secrets.proxmox_ve_sim_password }}"'>>input.tfvars
          echo "\n">>input

          echo "File args: $var_file_arg"
          echo "Input File args: $(cat input.tfvars)"
          terraform init -backend-config="key=${{ inputs.cluster }}-ci-simul-${{ steps.infra_names.outputs.simul_prefix }}.tfstate"
          terraform apply -auto-approve $var_file_arg -var-file=input.tfvars
          terraform refresh $var_file_arg -var-file=input.tfvars

          echo "${{ secrets.ssh_priv_key }}" > ~/.ssh/ci_priv_key.pem
          sudo chmod 600 ~/.ssh/ci_priv_key.pem

      - name: Gather Terraform outputs
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        id: infra_outputs
        shell: bash
        run: |
          ip=$(terraform output manager_ip_address)
          user=$(terraform output user)
          echo "host_ip=$(echo $ip | sed "s;\";;g")" >> $GITHUB_OUTPUT
          echo "host_user=$(echo $user | sed "s;\";;g")" >> $GITHUB_OUTPUT
          echo "ssh_connect_string=$(echo $user | sed "s;\";;g")@$(echo $ip | sed "s;\";;g")" >> $GITHUB_OUTPUT

      - name: Configure SSH
        id: remote_ssh_setup
        shell: bash
        run: |
          ssh-keygen -f ~/.ssh/known_hosts -R ${{ steps.infra_outputs.outputs.host_ip }} || true
          ssh-keyscan -H ${{ steps.infra_outputs.outputs.host_ip }} >> ~/.ssh/known_hosts || true

          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cloud-init status --wait; rm -rf ./${{ env.REMOTE_WORKSPACE_PATH }}; mkdir -p ./${{ env.REMOTE_WORKSPACE_PATH }}
          '

      - name: Prepare Devops provisioning slack message
        if: ${{ github.event_name != 'pull_request' }}
        id: pre_slack_infra
        run: |
          MESSAGE_ERR=":x: CI: ${GITHUB_REPOSITORY}, (${GITHUB_REF#refs/heads/}), build: $(cat product.version) is being impacted by an infrastructural issue. \
          Provisioning of fleet infrastructure failed. Please take a look! \
          Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          echo "msg_error=${MESSAGE_ERR}" >> $GITHUB_OUTPUT

      - name: Slack message failure
        if: ${{ failure() && github.event_name != 'pull_request' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "G0102LEV1CL"
          slack-message: ${{ steps.pre_slack_infra.outputs.msg_error }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}

      - name: Remote - Agent info
        id: agent_info_remote
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            ip=$(hostname -I | cut -d " " -f1)
            echo $ip '

      - name: Nvidia slack message
        id: nvidia_err_msg
        run: |
          echo "msg_error=Nvidia container error detected.\
          Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT

      - name: Remote - Detect Nvidia mismatch
        shell: bash
        id: nvidia_check
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -t '
              set -e
              Architecture="$(uname -m)"
              distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
              curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg --yes
              curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sed "s#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g" | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
              max_retries=12  # Maximum number of retries (12 retries with 5 seconds sleep = 1 minute)
              retries=0
              while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
                if [ $retries -ge $max_retries ]; then
                  echo "Reached maximum retry limit, exiting."
                  exit 1
                fi
                echo "Waiting for other software managers to finish... (retry: $retries)"
                retries=$((retries + 1))
                sleep 5
              done
              sudo apt-get update -q > /dev/null && sudo apt-get install -yq nvidia-docker2 nvidia-container-toolkit
          '
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
              sudo systemctl restart docker
              sleep 3
              docker run --gpus=all --rm nvcr.io/nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi 2>&1
              '

      - name: Slack message failure
        if: ${{ failure() && github.event_name != 'pull_request' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "G0102LEV1CL"
          slack-message: ${{ steps.nvidia_err_msg.outputs.msg_error }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}

      - name: Download component artifacts for patching
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/

      - name: Remote - Move component artifacts
        shell: bash
        run: scp -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -r ./artifacts ${{ steps.infra_outputs.outputs.ssh_connect_string }}:${{ env.REMOTE_WORKSPACE_PATH }}/
          
      - name: Remote - create execution folder
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            sudo rm -rf ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
            mkdir  -p ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
            sudo chmod -R 777 ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
          '
      
      - name: Remote - Login to Registry
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            docker login ${{ env.REGISTRY }} -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }}
          '

      - name: Remote - fetch stack tests
        id: infra_tests_setup
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            tests_dir=${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/stack_tests

            rm -rf $tests_dir
            mkdir -p $tests_dir
            sudo chmod -R 777 $tests_dir

            docker run -u root \
              -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }} \
              -i ${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
              fetch_by_tag \
              --repo ${{ inputs.test_repo_name }} \
              --version ${{ inputs.test_version }} \
              --gh_api_user ${{ secrets.auto_commit_user }} \
              --gh_api_pwd  ${{ secrets.auto_commit_pwd }} \
              --target_dir ${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}/stack_tests

            ls -la ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }} 
            sudo chmod 777 -R ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }} 

            # setup tests venv in a step that is always executed
            python3 -m venv "${tests_dir}"/test-venv --clear
            . "${tests_dir}"/test-venv/bin/activate
            # Temporary comment due to incomplete repo
            # pip install -r "${tests_dir}"/requirements.txt
            deactivate
          '

      - name: Remote - fetch product version
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            product_dir=${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/product

            rm -rf $product_dir
            mkdir -p $product_dir
            sudo chmod -R 777 $product_dir

            docker run -u root \
              -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }} \
              -i ${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
              fetch_product_by_version \
              --product_version_search ${{ inputs.vs_product_version_pattern}} \
              --repo ${{ inputs.vs_product_name }} \
              --gh_api_user ${{ secrets.auto_commit_user }} \
              --gh_api_pwd ${{ secrets.auto_commit_pwd }} \
              --target_dir ${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}/product

            ls -la ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }} 
            sudo chmod 777 -R ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

          '

      - name: Remote - Install
        id: install
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e

            export DISPLAY="$(w -oush | grep -Eo " :[0-9]+" | uniq | cut -d \  -f 2)"
            echo "Display detected (dinamic) is $DISPLAY"
            export DISPLAY=":0"
            echo "Display detected is $DISPLAY"

            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            export PATH="$HOME/.local/bin:$PATH"

            PRODUCT_NAME="$(echo ${{ inputs.vs_product_name }} | sed '\''s/^project-\(movai-\)\?//'\'' )"
            if [[ "$PRODUCT_NAME" == "studio" ]]; then
              PRODUCT_NAME="solution"
            fi
            export CONFIG_FILE_NAME="product/standalone-spawner-$PRODUCT_NAME-simulator-noetic.json"

            cp -r ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/* ./ && sudo rm -rf ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

            export USERSPACE_FOLDER_PATH="${{ env.USERSPACE_FOLDER_PATH }}"
            sudo mkdir -p $USERSPACE_FOLDER_PATH/.git;sudo chown 1000:1000 $USERSPACE_FOLDER_PATH/ -Rf
            export PUBLIC_IP="$(hostname -I | cut -d " " -f1)"
            export SIMULATION_ID="${{ env.SIMULATION_ID }}"
            export ROBOTNAME="ci_${{ inputs.component_name }}"
            sudo apt install jq -y
            jq --version
            jq '\''.robot.name = "$ROBOTNAME"'\'' $CONFIG_FILE_NAME > tmp.json && mv tmp.json $CONFIG_FILE_NAME

            # Enable debug logs of movai-service
            sudo mkdir -p /etc/movai/
            sudo sh -c "echo MOVAI_SERVICE_LOGGER_LEVEL=DEBUG >> /etc/movai/config.env"
            sudo chmod -R +r /etc/movai

            ls -la ${{ env.USERSPACE_FOLDER_PATH }}

            wget https://movai-scripts.s3.amazonaws.com/QuickStart_$(cat product/quickstart_version.txt).bash
            chmod +x ./QuickStart_$(cat product/quickstart_version.txt).bash
            ./QuickStart_$(cat product/quickstart_version.txt).bash --apps $(cat product/service_version.txt) $CONFIG_FILE_NAME
            MOVAI_USER="ci"
            MOVAI_PWD="4Iva6UHAQq9DGITj"
            for robot in $(movai-cli robots list); do
              movai-cli robots user "$robot" "$MOVAI_USER" "$MOVAI_PWD"
            done

            execution_status=$?
            exit $execution_status
            rm service_version.txt
          '
          echo "movai_user=ci" >> $GITHUB_OUTPUT
          echo "movai_pwd=4Iva6UHAQq9DGITj" >> $GITHUB_OUTPUT
          echo "robot_name=ci_${{ inputs.component_name }}" >> $GITHUB_OUTPUT


      - name: Remote - Post install patch
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            echo "Installing component ${{ inputs.component_name }} in spawner-${{ steps.install.outputs.robot_name }}-movai"
            docker cp ${{ env.REMOTE_WORKSPACE_PATH }}/artifacts/ spawner-${{ steps.install.outputs.robot_name }}-movai:/tmp/artifacts
            docker exec -u root spawner-${{ steps.install.outputs.robot_name }}-movai bash -c "dpkg -i /tmp/artifacts/*.deb"
          '

      # - name: test setup
      #   shell: bash
      #   run: |


      # - name: Run tests
      #   shell: bash
      #   run: |


      # - name: Collect tests artifacts
      #   if: always()
      #   shell: bash
      #   run: |


      - name: Remote - Collect platform artifacts
        if: always()
        shell: bash
        run: |
          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd ${{ env.REMOTE_WORKSPACE_PATH }}
            mkdir -p test_artifacts

            # for sanity
            docker ps -a

            for container in backend spawner messager-server monitoring redis-master redis-local influxdb haproxy; do
              CONTAINER_ID=$(docker ps -a --format '\''{{.Names}}'\'' --filter "name=^${container}-.*")
              docker logs "${CONTAINER_ID}" &> "${container}.log" || true
            done || true

            # movai-service
            journalctl -u movai-service --since '\''1hour ago'\'' &> "movai-service.log"

            # spawner (mobros firmware)
            journalctl -u movai-service -t mobros --since '\''1hour ago'\'' &> spawner-firmware.log || true
          '

      - name: Remote - Move test artifacts
        if: always()
        shell: bash
        run: |
          pwd
          scp -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -r ${{ steps.infra_outputs.outputs.ssh_connect_string }}:${{ env.REMOTE_WORKSPACE_PATH }}/test_artifacts test_artifacts
          ls -la

      - name: Upload test_artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: test_artifacts

      - name: Teardown remote vms (Proxmox)
        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
        if: ${{ inputs.debug_component_tests_keep_alive == false && always() }}
        shell: bash
        run: |
          attempts=3
          count=0
          while [ $count -lt $attempts ]; do
            var_file_arg='-var-file=../${{ steps.infra_env_configs_setup.outputs.target_dir }}/marvin/${{ inputs.cluster }}_simul_bpg.tfvars'
            terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars -var "fleet_peer_nr=0"
            exit_status=$?
            if [ $exit_status -eq 0 ]; then
              break
            elif [ $exit_status -eq 1 ]; then
              ((count++))
              echo "Retrying Terraform destroy (attempt $count)..."
            else
                  echo "Terraform destroy failed with exit status ${exit_status:-unknown}. Exiting..."
                  exit ${exit_status:-1}
            fi
          done
