name: Robotic Component pipeline
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      vs_product_name:
        required: true
        type: string
      vs_product_version_pattern:
        required: true
        type: string
      test_repo_name:
        required: true
        type: string
      test_version:
        required: true
        type: string
      test_set:
        required: true
        type: string
      cluster:
        required: false
        default: "mary"
        type: string
      debug_component_tests_keep_alive:
        required: false
        default: false
        type: boolean

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      proxmox_ve_sim_username:
        required: true
      proxmox_ve_sim_password:
        required: true
      ssh_priv_key:
        required: true
      slack_token_id:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: "4.0.0.13"
  GITHUB_API_USR: "OttoMation-Movai"
  USERSPACE_FOLDER_PATH: "$(pwd)/userspace"
  REMOTE_WORKSPACE_PATH: workspace
  CI_INTEGRATION_CONTAINER_VERSION: "registry.cloud.mov.ai/qa/ci-tools:4.0.0.31"
  CI_INTEGRATION_CONTAINER_WORKSPACE: "/opt/mov.ai/workspace"
  CI_INTEGRATION_EXECUTION_FOLDER: "$(pwd)/temp"
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_DEFAULT_REGION: "us-east-1"
  REGISTRY: registry.cloud.mov.ai
  PROVISION_INFRA_REPO: "devops-tf-proxmox-bpg"
  PROVISION_INFRA_VERSION: "2.0.0-17"
  PROVISION_INFRA_DIR: "provision_scripts"
  PROVISIONING_ENV_CONF_REPO: "devops-tf-env-conf"
  PROVISIONING_ENV_CONF_VERSION: "0.2.0-6"
  PROVISION_ENV_CONF_DIR: "infra_env_configs"
  SIMULATION_ID: CI
  SLACK_CHANNEL: "G0102LEV1CL"

jobs:
  Stack-tests:
    runs-on: simul-${{ inputs.cluster }}-queuer

    steps:
      - name: Cleanup Workspace
        uses: rtCamp/action-cleanup@master

      - name: Checkout
        uses: actions/checkout@v6



      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}
          registry: ${{ env.REGISTRY }}

      - name: Create execution folder
        shell: bash
        run: |
          sudo rm -rf ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
          mkdir  -p ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}
          sudo chmod -R 777 ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

      - name: Setup Infrastructure
        id: infra_setup
        uses: ./.github/actions/infrastructure-setup
        with:
          cluster_node: ${{ inputs.cluster }}
          infrastructure_identifier: "robotics-component-${{ inputs.component_name }}"
          fleet_usage: "ip-temp-simulation-fleet"
          provision_infra_repo: ${{ env.PROVISION_INFRA_REPO }}
          provision_infra_version: ${{ env.PROVISION_INFRA_VERSION }}
          provision_infra_env_repo: ${{ env.PROVISIONING_ENV_CONF_REPO }}
          provision_infra_env_version: ${{ env.PROVISIONING_ENV_CONF_VERSION }}
          ci_integration_scripts_version: ${{ env.CI_INTEGRATION_SCRIPTS_VERSION }}
          github_api_user: ${{ env.GITHUB_API_USR }}
          github_api_token: ${{ secrets.auto_commit_pwd }}
          proxmox_username: ${{ secrets.proxmox_ve_sim_username }}
          proxmox_password: ${{ secrets.proxmox_ve_sim_password }}
          proxmox_marvin_username: ${{ secrets.proxmox_ve_sim_username }}
          proxmox_marvin_password: ${{ secrets.proxmox_ve_sim_password }}
          proxmox_hel0_username: ${{ secrets.proxmox_ve_sim_username }}
          proxmox_hel0_password: ${{ secrets.proxmox_ve_sim_password }}
          proxmox_hel1_username: ${{ secrets.proxmox_ve_sim_username }}
          proxmox_hel1_password: ${{ secrets.proxmox_ve_sim_password }}
          aws_access_key: ${{ secrets.aws_access_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_access_key }}
          fleet_password: ""
          ssh_private_key: ${{ secrets.ssh_priv_key }}
          docker_container_version: ${{ env.CI_INTEGRATION_CONTAINER_VERSION }}
          ci_integration_execution_folder: ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

      - name: Prepare Devops provisioning slack message
        if: ${{ failure() && github.event_name != 'pull_request' }}
        id: pre_slack_infra
        run: |
          printf 'msg_error=:x: CI: %s, (%s)is being impacted by an infrastructural issue. Provisioning of Stack component pipeline infrastructure failed. Please take a look! Details: https://github.com/%s/actions/runs/%s\n' "${GITHUB_REPOSITORY}" "${GITHUB_REF#refs/heads/}" "${GITHUB_REPOSITORY}" "${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT

      - name: Slack message failure
        if: ${{ failure() && github.event_name != 'pull_request' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.pre_slack_infra.outputs.msg_error }}"
            }
          token: ${{ secrets.slack_token_id }}

      - name: Remote - Agent info
        id: agent_info_remote
        run: |
          ssh ${{ steps.infra_setup.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            ip=$(hostname -I | cut -d " " -f1)
            echo $ip '

      - name: Nvidia slack message
        id: nvidia_err_msg
        run: |
          printf 'msg_error=Nvidia container error detected. Details: https://github.com/%s/actions/runs/%s\n' "${GITHUB_REPOSITORY}" "${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT

      - name: Remote - Detect Nvidia mismatch
        shell: bash
        id: nvidia_check
        run: |
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -t '
              set -e
              Architecture="$(uname -m)"
              distribution=$(. /etc/os-release;echo "$ID$VERSION_ID")
              curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg --yes
              curl -s -L https://nvidia.github.io/libnvidia-container/"$distribution"/libnvidia-container.list | sed "s#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g" | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
              max_retries=12  # Maximum number of retries (12 retries with 5 seconds sleep = 1 minute)
              retries=0
              while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
                if [ "$retries" -ge "$max_retries" ]; then
                  echo "Reached maximum retry limit, exiting."
                  exit 1
                fi
                echo "Waiting for other software managers to finish... (retry: $retries)"
                retries=$((retries + 1))
                sleep 5
              done
              sudo apt-get update -q > /dev/null && sudo apt-get install -yq nvidia-docker2 nvidia-container-toolkit
          '
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
              sudo systemctl restart docker
              sleep 3
              docker run --gpus=all --rm nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi 2>&1
              '

      - name: Slack message failure
        if: ${{ failure() && github.event_name != 'pull_request' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "${{ steps.nvidia_err_msg.outputs.msg_error }}"
            }
          token: ${{ secrets.slack_token_id }}

      - name: Download component artifacts for patching
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/

      - name: Remote - Move component artifacts
        shell: bash
        run: scp -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -r ./artifacts "${{ steps.infra_setup.outputs.ssh_connect_string }}:${{ env.REMOTE_WORKSPACE_PATH }}/"

      - name: Remote - create execution folder
        shell: bash
        run: |
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd "${{ env.REMOTE_WORKSPACE_PATH }}"

            sudo rm -rf "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"
            mkdir -p "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"
            sudo chmod -R 777 "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"
          '

      - name: Remote - Login to Registry
        shell: bash
        run: |
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            docker login "${{ env.REGISTRY }}" -u "${{ secrets.registry_user }}" -p "${{ secrets.registry_password }}"
          '

      - name: Remote - fetch stack tests
        id: infra_tests_setup
        shell: bash
        run: |
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd "${{ env.REMOTE_WORKSPACE_PATH }}"

            tests_dir="${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/stack_tests"

            rm -rf "$tests_dir"
            mkdir -p "$tests_dir"
            sudo chmod -R 777 "$tests_dir"

            docker run -u root \
              -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":"${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}" \
              -i "${{ env.CI_INTEGRATION_CONTAINER_VERSION }}" \
              fetch_by_tag \
              --repo "${{ inputs.test_repo_name }}" \
              --version "${{ inputs.test_version }}" \
              --gh_api_user "${{ secrets.auto_commit_user }}" \
              --gh_api_pwd "${{ secrets.auto_commit_pwd }}" \
              --target_dir "${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}/stack_tests"

            ls -la "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"
            sudo chmod 777 -R "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"

            # setup tests venv in a step that is always executed
            python3 -m venv test-venv --clear
            . test-venv/bin/activate
            python3 -m pip install -r "$tests_dir/requirements.txt"
            deactivate

          '

      - name: Remote - fetch product version
        shell: bash
        run: |
          ssh "${{ steps.infra_setup.outputs.ssh_connect_string }}" -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd "${{ env.REMOTE_WORKSPACE_PATH }}"

            product_dir="${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/product"

            rm -rf "$product_dir"
            mkdir -p "$product_dir"
            sudo chmod -R 777 "$product_dir"

            docker run -u root \
              -v "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}":"${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}" \
              -i "${{ env.CI_INTEGRATION_CONTAINER_VERSION }}" \
              fetch_product_by_version \
              --product_version_search "${{ inputs.vs_product_version_pattern }}" \
              --repo "${{ inputs.vs_product_name }}" \
              --gh_api_user "${{ secrets.auto_commit_user }}" \
              --gh_api_pwd "${{ secrets.auto_commit_pwd }}" \
              --target_dir "${{ env.CI_INTEGRATION_CONTAINER_WORKSPACE }}/product"

            ls -la "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"
            sudo chmod 777 -R "${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}"

          '

      - name: Remote - Install
        id: install
        shell: bash
        run: |
          ssh ${{ steps.infra_setup.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e

            export DISPLAY="$(w -oush | grep -Eo " :[0-9]+" | uniq | cut -d \  -f 2)"
            echo "Display detected (dinamic) is $DISPLAY"
            export DISPLAY=":0"
            echo "Display detected is $DISPLAY"

            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            export PATH="$HOME/.local/bin:$PATH"

            PRODUCT_NAME="$(echo ${{ inputs.vs_product_name }} | sed '\''s/^project-\(movai-\)\?//'\'' )"
            if [[ "$PRODUCT_NAME" == "studio" ]]; then
              PRODUCT_NAME="solution"
            fi
            export CONFIG_FILE_NAME="product/standalone-spawner-$PRODUCT_NAME-simulator-noetic.json"

            cp -r ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}/* ./ && sudo rm -rf ${{ env.CI_INTEGRATION_EXECUTION_FOLDER }}

            export USERSPACE_FOLDER_PATH="${{ env.USERSPACE_FOLDER_PATH }}"
            sudo mkdir -p $USERSPACE_FOLDER_PATH/.git;sudo chown 1000:1000 $USERSPACE_FOLDER_PATH/ -Rf
            export PUBLIC_IP="$(hostname -I | cut -d " " -f1)"
            export SIMULATION_ID="${{ env.SIMULATION_ID }}"
            export ROBOTNAME="ci_${{ inputs.component_name }}"
            jq --version
            jq '\''.robot.name = "$ROBOTNAME"'\'' $CONFIG_FILE_NAME > tmp.json && mv tmp.json $CONFIG_FILE_NAME

            # Enable debug logs of movai-service
            sudo mkdir -p /etc/movai/
            sudo sh -c "echo MOVAI_SERVICE_LOGGER_LEVEL=DEBUG >> /etc/movai/config.env"
            sudo chmod -R +r /etc/movai

            ls -la ${{ env.USERSPACE_FOLDER_PATH }}

            wget https://movai-scripts.s3.amazonaws.com/QuickStart_$(cat product/quickstart_version.txt).bash
            chmod +x ./QuickStart_$(cat product/quickstart_version.txt).bash
            ./QuickStart_$(cat product/quickstart_version.txt).bash --apps $(cat product/service_version.txt) $CONFIG_FILE_NAME
            MOVAI_USER="ci"
            MOVAI_PWD="4Iva6UHAQq9DGITj"
            for robot in $(movai-cli robots list); do
              movai-cli robots user "$robot" "$MOVAI_USER" "$MOVAI_PWD"
            done

            execution_status=$?
            exit $execution_status
            rm service_version.txt
          '
          echo "movai_user=ci" >> $GITHUB_OUTPUT
          echo "movai_pwd=4Iva6UHAQq9DGITj" >> $GITHUB_OUTPUT
          echo "robot_name=ci_${{ inputs.component_name }}" >> $GITHUB_OUTPUT


      - name: Remote - Run tests
        shell: bash
        run: |
          ssh ${{ steps.infra_setup.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e

            cd ${{ env.REMOTE_WORKSPACE_PATH }}

            . test-venv/bin/activate

            cd stack_tests

            pytest ${{ inputs.test_set }} \
              --component-pkgs ../artifacts \
              --movai-user ${{ steps.install.outputs.movai_user }} \
              --movai-pw ${{ steps.install.outputs.movai_pwd }}

            deactivate
          '

      - name: Remote - Collect platform artifacts
        if: always()
        shell: bash
        run: |
          ssh ${{ steps.infra_setup.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
            set -e
            cd ${{ env.REMOTE_WORKSPACE_PATH }}
            mkdir -p tests_artifacts
            cd tests_artifacts

            # for sanity
            docker ps -a

            for container in backend spawner message-server monitoring redis-master redis-local influxdb haproxy; do
              CONTAINER_ID=$(docker ps -a --format '\''{{.Names}}'\'' --filter "name=^${container}-.*")
              docker logs "${CONTAINER_ID}" &> "${container}.log" || true
            done || true

            # movai-service
            journalctl -u movai-service --since '\''1hour ago'\'' &> "movai-service.log"

            # spawner (mobros firmware)
            journalctl -u movai-service -t mobros --since '\''1hour ago'\'' &> spawner-firmware.log || true

            pwd
            ls -la
          '

      - name: Remote - Move test artifacts
        if: always()
        shell: bash
        run: scp -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no -r ${{ steps.infra_setup.outputs.ssh_connect_string }}:${{ env.REMOTE_WORKSPACE_PATH }}/tests_artifacts tests_artifacts

      - name: Upload test_artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests_artifacts
          path: tests_artifacts

      - name: Teardown remote vms (Proxmox)
        working-directory: ${{ steps.infra_setup.outputs.provision_infra_dir }}
        if: ${{ inputs.debug_component_tests_keep_alive == false && always() }}
        shell: bash
        run: |
          attempts=3
          count=0
          while [ $count -lt $attempts ]; do
            terraform destroy -auto-approve
            exit_status=$?
            if [ $exit_status -eq 0 ]; then
              break
            elif [ $exit_status -eq 1 ]; then
              ((count++))
              echo "Retrying Terraform destroy (attempt $count)..."
            else
                  echo "Terraform destroy failed with exit status ${exit_status:-unknown}. Exiting..."
                  exit ${exit_status:-1}
            fi
          done
