name: Build Packer images
on:
  workflow_call:
    inputs:
        product_name:
          required: true
          type: string
        branch_name:
          required: true
          type: string
    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      nexus_publisher_user:
        required: true
      nexus_publisher_password:
        required: true
      gh_token:
        required: true

env:
  CI_INTEGRATION_SCRIPTS_VERSION: '2.1.0.13'
  GITHUB_API_USR: 'OttoMation-Movai'


jobs:
  Validate-boostrap-configs:
    runs-on: ubuntu-20.04
    container:
      image: registry.aws.cloud.mov.ai/devops/py-buildserver:latest
      credentials:
        username: ${{secrets.registry_user}}
        password: ${{secrets.registry_password}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Manifest
      shell: bash
      run: |
            apt install -y yamllint
            yamllint product-manifest.yaml
            cat product-manifest.yaml
    
    - name: Bootstraping simulator metadata
      run: |
          python3 -m pip install integration-pipeline==$CI_INTEGRATION_SCRIPTS_VERSION --ignore-installed
                  export PATH="$HOME/.local/bin:$PATH"
          rm -rf simulator_artifacts ci_artifacts

          integration-pipeline merge_manifest_dependency \
                --dependency_name product-platform \
                --gh_api_user $GITHUB_API_USR \
                --gh_api_pwd ${{ secrets.auto_commit_pwd }} \
                --auto_fetch

          integration-pipeline generate_meta_simulator_artifacts \
                --manifest_platform_base_key product-dependencies \
                --product_name ${{ inputs.product_name }} \
                --branch ${{ inputs.branch_name }} \
                --update_simulator \
                --docker_registry registry.cloud.mov.ai

          mkdir simulator_artifacts
          cp ci_artifacts/* ./simulator_artifacts
    - name: Stash sim_configs
      uses: actions/upload-artifact@v2
      with:
        name: sim_configs
        path: simulator_artifacts/*

  Build-Spawner:
    needs: [Validate-boostrap-configs]
    runs-on: integration-pipeline
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Manifest
      shell: bash
      run: |
            cat product-manifest.yaml
  
  Build-Simulator:
    needs: [Validate-boostrap-configs]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Manifest
      shell: bash
      run: |
            cat product-manifest.yaml

  publish:
    needs: [Build-Spawner, Build-Simulator]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Manifest
      shell: bash
      run: |
            cat product-manifest.yaml