name: Build and pack Npm components 
on:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: string
        default: 'false'
       

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      gh_token:
        required: true
      sonar_token:
        required: true

jobs:
  Build:

    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/devops/npm-buildserver:latest
      options: --user root
      credentials:
        username: ${{secrets.registry_user}} 
        password: ${{secrets.registry_password}}

    steps:
    - name: Checkout    
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.NPM_TOKEN }}

    - name: Raise App version
      run: |
        git config --global user.name '${{ secrets.auto_commit_user }}'
        git config --global user.email '${{ secrets.auto_commit_mail }}'
        npm version patch --no-git-tag-version

    - name: Setup Github as proxy Registry 
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com/mov-ai'

    - name: Install dependencies
      run: npm ci --loglevel verbose

    - name: Build
      run: npm run build

    - name: Check NPM log on failure
      if: ${{ failure() }}
      run: cat /github/home/.npm/_logs/*.log
    # Skip tests for now
    #- name: Run tests
    #  run: npm run test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1.0.0
      env:
        SONAR_TOKEN: ${{ secrets.sonar_token }}
        SONAR_HOST_URL: https://sonarqube.aws.cloud.mov.ai
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.organization=MOV-AI
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.verbose=true
          -Dsonar.sources=.
          -Dsonar.scm.provider=git
          -Dsonar.qualitygate.wait=true
          -Dsonar.qualitygate.timeout=300

    - name: Link to SonarQube Dashboard
      shell: bash
      run: |
        echo "Please check report here: https://sonarqube.aws.cloud.mov.ai/dashboard?id=${{ github.event.repository.name }}"
      id: sonar_links

    - name: Publish
      if: ${{ inputs.deploy == 'true' }}
      run: npm publish

    

  Post-publish:
    if: ${{ inputs.deploy == 'true' }}
    runs-on: ubuntu-20.04
    needs:  [Build]
    container:
      image: registry.cloud.mov.ai/devops/npm-buildserver:latest
      options: --user root
      credentials:
        username: ${{secrets.registry_user}} 
        password: ${{secrets.registry_password}}

    steps:
    - name: Checkout    
      if: ${{ inputs.deploy == 'true' }}
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        submodules: recursive
        
    - name: Raise App version
      run: |
        git config --global user.name 'Automatic Raise'
        git config --global user.email 'test@test'
        npm version patch -m "Automatic Bump of build version" 
        git add package.*
        git push
