name: Build Offline ISO 
on:
  workflow_call:
    inputs:
      OS_NAME:
        type: string
        required: true
      OS_VERSION:
        type: string
        required: true
      OS_FULL_VERSION:
        type: string
        required: true
      HOSTNAME:
        type: string
        required: true
      PRODUCT_NAME:
        type: string
        required: true
      PRODUCT_VERSION:
        type: string
        required: true
    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      registry_user:
        required: true
      registry_password:
        required: true
      nexus_publisher_user:
        required: true
      nexus_publisher_password:
        required: true
jobs:
  Validate-features:
    runs-on: packer-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Agent info
        run: |
          echo "public ip: $(curl ipinfo.io/ip)"
          echo "private ip: $(hostname -I | awk '{print $1}')"

      # - name: Lint with shellcheck
      #   uses: azohra/shell-linter@latest
      #   with:
      #     path: ./*.bash

      - name: Create config file
        run: |
          echo "UBUNTU_NAME=${{ inputs.OS_NAME }}" > config.cfg
          echo "UBUNTU_VERSION=${{ inputs.OS_VERSION }}" >> config.cfg
          echo "UBUNTU_VERSION_BUILD=${{ inputs.OS_FULL_VERSION }}" >> config.cfg
          echo "HOSTNAME=${{ inputs.HOSTNAME }}" >> config.cfg
          echo "SSID=MOVAIPT" >> config.cfg
          echo "PASSWORD=your_password" >> config.cfg
          echo "WIFI_INTERFACE=wlp0s20f3" >> config.cfg
          echo "ETHERNET_INTERFACE=enp7s0" >> config.cfg
          echo "DHCP4=yes" >> config.cfg
          echo "OPTIONAL=true" >> config.cfg


      - name: Fetch platform artifacts
        run: |
          wget https://movai-scripts.s3.amazonaws.com/Deployment_Toolkit.bash
          chmod +x Deployment_Toolkit.bash
          ./Deployment_Toolkit.bash
        env:
          DOCKER_REG_USER: ${{ secrets.registry_user }}
          DOCKER_REG_PWD: ${{ secrets.registry_password }}
          NX_API_USR: ${{ secrets.nexus_publisher_user }}
          NX_API_PWD: ${{ secrets.nexus_publisher_password }}
          GITHUB_API_USR: ${{ secrets.auto_commit_user }}
          GITHUB_API_PWD: ${{ secrets.auto_commit_pwd }}
          PRODUCT_NAME: ${{ inputs.PRODUCT_NAME }}
          PRODUCT_VERSION: ${{ inputs.PRODUCT_VERSION }}


      - name: Run the script
        run: |
          mv offline_install_artifacts/* .
          ./mkisofs-movai-autoinstall.bash config.cfg
    
      - name: Clean up
        if: always()
        run: |
          docker rm -f $(docker ps -a -q) || true
          docker rmi -f $(docker images -q) || true


    