name: Build Packer images
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        default: 'false'
      image_type_list:
        required: true
        type: string

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      packer_build_server:
        required: true
      packer_token_id:
        required: true
      packer_token_secret:
        required: true
      minio_key_id:
        required: false
      minio_secret_key_id:
        required: false

env:
  # slack channel movai-projects
  SLACK_CHANNEL: ${{ inputs.overwrite_slack_channel }}
  # development slack channel
  #SLACK_CHANNEL: "C05K2KF1UP8"
  MINIO_S3_URL: "https://s3.mov.ai"   

jobs:
  Build:
    runs-on: packer-runner
    
    strategy:
      matrix:
        image_type: ${{ fromJSON(inputs.image_type_list) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Packer Validate
        run: |
          packer init .
          packer validate .

      - name: Packer build
        if: ${{ inputs.deploy == 'true' }}
        shell: bash
        run: |
          # IMAGES_FILES="$(find -L ${{ matrix.image_type }} -name "*.pkr.hcl" | awk '{ print length, $0 }' | sort -rn | cut -d" " -f2-)"
          # for image_file in $IMAGES_FILES; do
            image_name=$(echo $image_file | sed "s|.pkr.hcl||g" | sed "s|${{ matrix.image_type }}/||g")
            echo "Running ../build.bash $image_name.pkr.hcl $image_name-v$(cat $GITHUB_WORKSPACE/version).img" 
            ./build.bash ${{ matrix.image_type }}/$image_name.pkr.hcl $image_name-v$(cat $GITHUB_WORKSPACE/version).img
          # done
  

      - name: Stash build artifacts (Minio)
        # if: ${{ always() &&  inputs.with_simulation_tests }}
        continue-on-error: true
        shell: bash
        run: |
          aws \
          --endpoint-url ${{ env.MINIO_S3_URL }} \
          s3 \
          cp \
          ${{ matrix.image_type }}/output/ \
          s3://ci-artifacts/${{ github.repository }}/${{ github.run_id}}/${{ github.job }}/attempts/${{ github.run_attempt }} \
          --recursive
        working-directory: "${{ inputs.build_dir }}"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.minio_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.minio_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_DEFAULT_OUTPUT: "none"  

      - name: Commit raise
        if: ${{ inputs.deploy == 'true' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git config --global user.name '${{ secrets.auto_commit_user }}'
          git config --global user.email '${{ secrets.auto_commit_mail }}'
          git config --global user.password ${{ secrets.auto_commit_pwd }}
          echo "GIT_USER=${{ secrets.auto_commit_user }}:${{ secrets.auto_commit_pwd }}" >> $GITHUB_ENV
          git pull
          git add version
          git commit -m "[skip actions] Automatic Bump of template id"
          git push --force-with-lease
        working-directory: "${{ inputs.build_dir }}"
