name: Build Packer images
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        default: 'false'
      build_dir:
        required: true
        type: string
        default: './packer/qemu'

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      auto_commit_pwd:
        required: true
      packer_build_server:
        required: true
      packer_token_id:
        required: true
      packer_token_secret:
        required: true
      minio_key_id:
        required: false
      minio_secret_key_id:
        required: false

env:
  # slack channel movai-projects
  SLACK_CHANNEL: ${{ inputs.overwrite_slack_channel }}
  # development slack channel
  #SLACK_CHANNEL: "C05K2KF1UP8"
  MINIO_S3_URL: "https://s3.mov.ai"   

jobs:
  Build:
    runs-on: packer-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Packer Validate
        run: |
          packer init .
          packer validate .
        working-directory: "${{ inputs.build_dir }}"
      
      - name: Packer Qemu seed
        run: |
          packer build -force packer_qemu.seed.pkr.hcl
        working-directory: "${{ inputs.build_dir }}"

      - name: Packer build
        if: ${{ inputs.deploy == 'true' }}
        run: |
          packer build -force ubuntu.pkr.hcl
        working-directory: "${{ inputs.build_dir }}"

      - name: Stash QA artifacts (Minio)
        # if: ${{ always() &&  inputs.with_simulation_tests }}
        continue-on-error: true
        shell: bash
        run: |
          aws \
          --endpoint-url ${{ env.MINIO_S3_URL }} \
          s3 \
          cp \
          output/ \
          s3://ci-artifacts/${{ github.repository }}/${{ github.run_id}}/${{ github.job }}/attempts/${{ github.run_attempt }} \
          --recursive
          --content-type="text/plain"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.minio_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.minio_secret_key_id }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_DEFAULT_OUTPUT: "none"  

      - name: Commit raise
        if: ${{ inputs.deploy == 'true' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git config --global user.name '${{ secrets.auto_commit_user }}'
          git config --global user.email '${{ secrets.auto_commit_mail }}'
          git config --global user.password ${{ secrets.auto_commit_pwd }}
          echo "GIT_USER=${{ secrets.auto_commit_user }}:${{ secrets.auto_commit_pwd }}" >> $GITHUB_ENV
          git pull
          git add version
          git commit -m "[skip actions] Automatic Bump of template id"
          git push --force-with-lease
        working-directory: "${{ inputs.build_dir }}"
