name: Build Packer images
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        default: 'false'
      build_dir:
        required: true
        type: string
        default: './packer/proxmox'

    secrets:
      auto_commit_user:
        required: true
      auto_commit_mail:
        required: true
      packer_build_server:
        required: true
      packer_token_id:
        required: true
      packer_token_secret:
        required: true

jobs:
  Build:
    runs-on: packer-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Raise Template identifier
        if: ${{ inputs.deploy == 'true' }}
        id: raise
        shell: bash
        run: |
          TEMPLATE_ID=$(cat version)
          if [ ${TEMPLATE_ID: -2} ==  99 ]
          then
            
            template_prefix=$(echo "${TEMPLATE_ID}" | head -c2)
            TEMPLATE_ID="$template_prefix"
            TEMPLATE_ID+="00"
          fi
          TEMPLATE_ID=$(($TEMPLATE_ID+1))
          echo "Raised to $TEMPLATE_ID"
          echo "$TEMPLATE_ID" > version
          echo ::set-output name=RAISED_VERSION::$TEMPLATE_ID
        working-directory: "${{ inputs.build_dir }}"

      - name: Packer Validate
        run: |
          packer validate \
            -var 'vm_id=0000' \
            -var 'proxmox_api_url=${{secrets.packer_build_server}}' \
            -var 'proxmox_api_token_id=${{secrets.packer_token_id}}' \
            -var 'proxmox_api_token_secret=${{secrets.packer_token_secret}}' .
        working-directory: "${{ inputs.build_dir }}"

      - name: Packer build
        if: ${{ inputs.deploy == 'true' }}
        run: |
          packer build \
            -var 'vm_id=${{steps.raise.outputs.RAISED_VERSION}}' \
            -var 'proxmox_api_url=${{secrets.packer_build_server}}' \
            -var 'proxmox_api_token_id=${{secrets.packer_token_id}}' \
            -var 'proxmox_api_token_secret=${{secrets.packer_token_secret}}' .
        working-directory: "${{ inputs.build_dir }}"

      - name: Commit raise
        if: ${{ inputs.deploy == 'true' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git config --global user.name '${{ secrets.auto_commit_user }}'
          git config --global user.email '${{ secrets.auto_commit_mail }}'
          git pull
          git add version 
          git commit -m "Automatic Bump of template id"
          git push
        working-directory: "${{ inputs.build_dir }}"
