name: pre-commit

on:
  push:
    branches:
      - 'v*'
  pull_request:
    branches:
      - 'v*'

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: MOV-AI/.github/.github/actions/pre-commit@v3