name: Build and run tests from a Python package
on:
  workflow_call:
    inputs:
      test_set:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: false
      nightly:
        required: false
        type: boolean
        default: false
      slack_channel_nightly_msg:
        required: false
        type: string
        default: 'C02PB9A9F45'
    secrets:
      jira_username:
        required: true
      jira_password:
        required: true
      xray_clientid:
        required: true
      xray_secret:
        required: true
      auto_commit_user:
        required: false # only when deploy true
      auto_commit_mail:
        required: false # only when deploy true
      auto_commit_password:
        required: false
      registry_user:
        required: true
      registry_password:
        required: true
      nexus_publisher_user:
        required: true
      nexus_publisher_password:
        required: true
      gh_token:
        required: true
      sonar_token:
        required: true
      slack_token_id:
        required: true

jobs:
  Validate-features:
    if: ${{ inputs.deploy == false }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Feature file validation
        shell: bash
        env:
          XRAY_CLIENTID: ${{ secrets.xray_clientid }}
          XRAY_SECRET: ${{ secrets.xray_secret }}
          JIRA_USERNAME: ${{ secrets.jira_username }}
          JIRA_PASSWORD: ${{ secrets.jira_password }}
        run: |
          # create virtual environment
          python3 -m venv venv --clear
          . venv/bin/activate

          # install tests requirements in venv
          pip install \
            -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple \
            --extra-index-url https://pypi.org/simple \
            .

          xray download ${{ inputs.test_set }}
          xray compare ./qa_install_tests/tests/feature/

  CI:
    uses: MOV-AI/.github/.github/workflows/py-workflow.yml@v2.3
    with:
      PYTHON_VERSION: "3.10"
      deploy: ${{ inputs.deploy }}
      run_black: true
      pre_commit: true
    secrets:
      auto_commit_user: ${{ secrets.auto_commit_user }}
      auto_commit_mail: ${{ secrets.auto_commit_mail }}
      auto_commit_password: ${{ secrets.auto_commit_password }}
      registry_user: ${{ secrets.registry_user }}
      registry_password: ${{ secrets.registry_password }}
      nexus_publisher_user: ${{ secrets.nexus_publisher_user }}
      nexus_publisher_password: ${{ secrets.nexus_publisher_password }}
      gh_token: ${{ secrets.gh_token }}
      sonar_token: ${{ secrets.sonar_token }}

  Install-Tests:
    if: ${{ inputs.deploy == false }}
    needs: CI
    runs-on: qa-runner

    steps:
      - name: Agent info
        id: agent_info
        run: |
          echo "ip=$(hostname -I | awk '{print $1}')" | tee $GITHUB_OUTPUT

      - name: Cleanup Workspace
        uses: rtCamp/action-cleanup@master

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages

      - name: Install package
        shell: bash
        run: |
          python3 -m venv .ci-venv --clear
          . .ci-venv/bin/activate
          pip install packages/*.whl

      - name: Tests
        shell: bash
        run: |
          . .ci-venv/bin/activate
          python3 -m pytest --full-clean --pyargs qa_install_tests.tests

      - name: Save docker container logs
        if: always()
        shell: bash
        run: |
          # for sanity
          docker ps -a

          # save all container logs and inspect
          CONTAINERS=$(docker ps -a --format '{{.Names}}')
          for container in ${CONTAINERS}; do
              docker logs "${container}" &> "${container}.log" || true
              docker inspect "${container}" &> "${container}-inspect.log"
          done || true

          # movai-service
          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"

          # spawner (mobros firmware)
          journalctl -u movai-service -t mobros --since '1hour ago' &> spawner-firmware.log || true

      - name: Collect artifacts
        if: always()
        shell: bash
        run: |
          rm -rf qa_artifacts
          mkdir qa_artifacts

          cp -r tests_artifacts/ qa_artifacts/ || true

          cp *.log ./qa_artifacts/ || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa_artifacts
          path: qa_artifacts/*

      - name: Remove robots
        if: always()
        shell: bash
        run: |
          movai remove --all

  Slack-Message-Result:
    runs-on: ubuntu-22.04
    needs:  [Validate-features, Install-Tests]
    if: ${{ always() && inputs.nightly }}
    steps:
      - name: Prepare slack variables
        id: pre_slack
        run: |
          MESSAGE=":white_check_mark: CI: ${GITHUB_REPOSITORY} (${GITHUB_REF#refs/heads/}), stable :sunny: Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          MESSAGE_ERR=":x: CI: ${GITHUB_REPOSITORY}, (${GITHUB_REF#refs/heads/}), unstable :rain_cloud: Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          echo "msg=$MESSAGE" >> $GITHUB_OUTPUT
          echo "msg_error=$MESSAGE_ERR" >> $GITHUB_OUTPUT

      - name: Slack message success
        if: ${{ inputs.nightly && ( needs.Validate-features.result == 'success' && needs.Install-Tests.result == 'success' ) }}
        uses: slackapi/slack-github-action@v3
        with:
          channel-id: ${{ inputs.slack_channel_nightly_msg }}
          slack-message: ${{ steps.pre_slack.outputs.msg }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}

      - name: Slack message failure
        if: ${{ inputs.nightly && ( needs.Validate-features.result == 'failure' || needs.Install-Tests.result == 'failure' ) }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ inputs.slack_channel_nightly_msg }}
          slack-message: ${{ steps.pre_slack.outputs.msg_error }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}
