name: UI Tests
on:
  workflow_call:
    inputs:
      install_tests_ref:
        required: true
        type: string
        description: Install tests reference to use
      test_set:
        required: true
        type: string
        description: Test set to execute
    secrets:
      gh_token:
        required: true
      slack_token_id:
        required: true
      jira_username:
        required: true
      jira_password:
        required: true
      xray_clientid:
        required: true
      xray_secret:
        required: true

jobs:
  Validate-features:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Feature file validation
        shell: bash
        env:
          XRAY_CLIENTID: ${{ secrets.xray_clientid }}
          XRAY_SECRET: ${{ secrets.xray_secret }}
          JIRA_USERNAME: ${{ secrets.jira_username }}
          JIRA_PASSWORD: ${{ secrets.jira_password }}
        run: |
          # create virtual environment
          rm -rf venv
          python3 -m venv venv
          . venv/bin/activate

          # install tests requirements in venv
          pip install \
            -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple \
            --extra-index-url https://pypi.org/simple \
            -r requirements.txt

          python3 testcasemanagement/testcase_importer.py --target ${{ inputs.test_set }}
          python3 testcasemanagement/feature_file_processor.py --validate

          # deactivate venv
          deactivate

  Run-tests:
    runs-on: integration-pipeline
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Agent info
        id: agent_info
        run: |
          ip_tmp=$(hostname -I | awk '{print $1}')
          echo $ip_tmp
          #echo ::set-output name=ip::$ip
          echo "ip=$ip_tmp" >> $GITHUB_OUTPUT

      - name: Update/upgrade host packages
        run: |
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do echo Waiting for other software managers to finish... ; sleep 5;done
          sudo apt-get update
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do echo Waiting for other software managers to finish... ; sleep 5;done
          sudo apt-get upgrade -y

          # needed for pre-commit execution
          sudo apt install python-is-python3

      - name: Check if pre-commit config exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".pre-commit-config.yaml"

      - name: Run pre-commit
        if: steps.check_files.outputs.files_exists == 'true'
        uses: pre-commit/action@v3.0.0

      - name: Setup venv
        shell: bash
        run: |
          # create virtual environment
          rm -rf venv
          python3 -m venv venv
          . venv/bin/activate

          # install tests requirements in venv
          pip install -r requirements.txt

          # deactivate venv
          deactivate

      - name: Setup QA install tests
        uses: actions/checkout@v3
        with:
          repository: MOV-AI/qa_install_tests
          ref: refs/heads/${{ inputs.install_tests_ref }}
          path: qa_install_tests
          token: ${{ secrets.gh_token }}

      - name: Install tests
        id: install
        working-directory: qa_install_tests
        shell: bash
        run: |
          # create virtual environment for testing
          python3 -m venv venv
          . venv/bin/activate

          # install tests requirements in venv
          pip install -r requirements.txt

          # tests execution
          pytest tests/ \
            -k 'AMR_installation_validator' \
            --installPath="." \
            --jsonConfigFilePath="config/platform_example_script.json"

          # remove virtual environment
          deactivate
          rm -rf venv

          user=$(cat results/credentials.txt | awk -F: '{print $1}')
          pwd=$(cat results/credentials.txt | awk -F: '{print $2}')
          #echo ::set-output name=movai_user::$user
          #echo ::set-output name=movai_pwd::$pwd
          echo "movai_user=$user" >> $GITHUB_OUTPUT
          echo "movai_pwd=$pwd" >> $GITHUB_OUTPUT

      - name: UI tests
        id: ui
        shell: bash
        run: |
          # install test dependencies on host
          sudo apt install -y --allow-downgrades python3-rosnode python3-rosparam python3-rostopic
          export PYTHONPATH="${PYTHONPATH}:/usr/lib/python3/dist-packages"

          # activate venv
          . venv/bin/activate

          # install test dependencies on spawner
          if [ -f apt-requirements.txt ]; then
            ## get spawner container name
            CONTAINER_ID=$(docker ps --format '{{.Names}}' --filter "name=^spawner-.*")
            ## get apt dependencies
            APT_DEPS=$(cat apt-requirements.txt | tr "\n" " ")
            ## install
            docker exec -t "${CONTAINER_ID}" bash -c "
              sudo apt update
              sudo apt install -y ${APT_DEPS}
            "
          fi

          # tests execution
          pytest \
            --ignore qa_install_tests \
            --hub_url http://selenoid-ui.hel.mov.ai \
            --base_url https://${{ steps.agent_info.outputs.ip }}/ \
            --movai-user ${{ steps.install.outputs.movai_user }} \
            --movai-pw ${{ steps.install.outputs.movai_pwd }}

          # remove virtual environment
          deactivate

      - name: Save docker container logs
        if: always()
        shell: bash
        run: |
          # for sanity
          docker ps -a

          # backend
          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^backend-.*")
          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"

          # spawner
          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"

          # movai-service
          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"

      - name: Stash QA artifacts
        if: always()
        shell: bash
        run: |
          # cleanup
          rm -rf qa_artifacts

          # tests artifacts
          # *.log and *.zip might not exist if the test fails early
          mkdir -p qa_artifacts
          cp -r *.log ./qa_artifacts || true
          cp -r *.tar ./qa_artifacts || true

          # install
          mkdir -p qa_artifacts/install
          cp -r qa_install_tests/results/*.log ./qa_artifacts/install/ || true
          cp -r qa_install_tests/results/*.zip ./qa_artifacts/install/ || true
          cp -r qa_install_tests/results/test_report_*.html ./qa_artifacts/install/ || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: qa_artifacts_ui_tests
          path: qa_artifacts/*

      - name: Remove robots
        if: always()
        shell: bash
        run: |
          for robot in $(movai-cli robots list); do
            movai-cli robots stop $robot
            sleep 5
            movai-cli robots remove $robot
          done || true

      - name: Docker cleanups
        if: always()
        shell: bash
        run: |
          docker system prune -f
          docker image prune --all -f
