name: UI Tests
on:
  workflow_call:
    inputs:
      install_tests_ref:
        required: true
        type: string
        description: Install tests reference to use
      test_set:
        required: true
        type: string
        description: Test set to execute
    secrets:
      gh_token:
        required: true
      slack_token_id:
        required: true
      jira_username:
        required: true
      jira_password:
        required: true
      xray_clientid:
        required: true
      xray_secret:
        required: true

jobs:
  Validate-features:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Feature file validation
        shell: bash
        env:
          XRAY_CLIENTID: ${{ secrets.XRAY_CLIENTID }}
          XRAY_SECRET: ${{ secrets.XRAY_SECRET }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: |
          # create virtual environment
          rm -rf venv
          python3 -m venv venv
          . venv/bin/activate
          # install tests requirements in venv
          pip install \
            -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple \
            --extra-index-url https://pypi.org/simple \
            -r requirements.txt
          xray download QAP-3111
          xray compare ./tests/feature/
          # deactivate venv
          deactivate
  Run-tests:
    runs-on: qa-runner
    steps:
      - name: Cleanup Workspace
        uses: rtCamp/action-cleanup@master

      - name: Checkout
        uses: actions/checkout@v3

      - name: Agent info
        id: agent_info
        run: |
          ip_tmp=$(hostname -I | awk '{print $1}')
          echo $ip_tmp
          #echo ::set-output name=ip::$ip
          echo "ip=$ip_tmp" >> $GITHUB_OUTPUT
      - name: Update/upgrade host packages
        run: |
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do echo Waiting for other software managers to finish... ; sleep 5;done
          sudo apt-get update
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do echo Waiting for other software managers to finish... ; sleep 5;done
          sudo apt-get upgrade -y
          # needed for pre-commit execution
          sudo apt install python-is-python3
      - name: Check if pre-commit config exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".pre-commit-config.yaml"

      - name: Setup environment
        shell: bash
        run: |
          # create virtual environment
          rm -rf venv
          python3 -m venv venv
          . venv/bin/activate
          # install tests requirements in venv
          pip install -r requirements.txt
          # deactivate venv
          deactivate
          # install test dependencies on host
          sudo apt install -y --allow-downgrades python3-rosnode python3-rosparam python3-rostopic tcpdump pcap2har
          sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
      - name: UI tests
        id: ui
        shell: bash
        run: |
          export PYTHONPATH="${PYTHONPATH}:/usr/lib/python3/dist-packages"
          # activate venv
          . venv/bin/activate
          # tests execution
          pytest \
            --hub_url http://selenoid-ui.hel.mov.ai \
            --base_url https://${{ steps.agent_info.outputs.ip }}/ \
            --install-platform
          # remove virtual environment
          deactivate
      - name: Save docker container logs
        if: always()
        shell: bash
        run: |
          # for sanity
          docker ps -a
          # save all container logs and inspect
          CONTAINERS=$(docker ps -a --format '{{.Names}}')
          for container in ${CONTAINERS}; do
              docker logs "${container}" &> "${container}.log" || true
              docker inspect "${container}" &> "${container}-inspect.log"
          done || true
          # movai-service
          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
          # spawner (mobros firmware)
          journalctl -u movai-service -t mobros --since '1hour ago' &> spawner-firmware.log || true
      - name: Stash QA artifacts
        if: always()
        shell: bash
        run: |
          # cleanup
          rm -rf qa_artifacts
          # tests artifacts
          # *.log and *.zip might not exist if the test fails early
          mkdir -p qa_artifacts
          cp -r *.log ./qa_artifacts || true
          cp -r *.tar ./qa_artifacts || true
          cp -r *.json ./qa_artifacts || true
          cp -r *.pcap ./qa_artifacts || true
          cp -r *.har ./qa_artifacts || true
          cp -r *.html ./qa_artifacts || true
          # install
          mkdir -p qa_artifacts/install
          cp -r qa_install_tests/results/*.log ./qa_artifacts/install/ || true
          cp -r qa_install_tests/results/*.zip ./qa_artifacts/install/ || true
          cp -r qa_install_tests/results/test_report_*.html ./qa_artifacts/install/ || true
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: qa_artifacts_ui_tests
          path: qa_artifacts/*
          retention-days: 3

      - name: Remove robots
        if: always()
        shell: bash
        run: |
          rm -rf test_robot
          for robot in $(movai-cli robots list); do
            movai-cli robots stop $robot
            sleep 5
            movai-cli robots remove $robot
          done || true
      - name: Docker cleanups
        if: always()
        shell: bash
        run: |
          docker system prune -f
          docker image prune --all -f
