name: "Test: docker login"
on:
  push:
    branches: [feat/ansible_vault]
env:
  REGISTRY: "registry.lis.mov.ai"

jobs:
  Test-Docker-Login:
    runs-on: simul-mary-queuer
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Agent info
        id: agent_info
        run: |
          echo "ip=$(hostname -I | awk '{print $1}')" | tee $GITHUB_OUTPUT

      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PORTUS_APP_USER }}
          password: ${{ secrets.PORTUS_APP_TOKEN }}
          registry: ${{ env.REGISTRY }}
